import type { PortDefinition } from "@ai-native-flow/flow-ir";
import type { StudioFieldLocale } from "./fields/fieldLabels.js";

export interface StudioPortLabelDictionary {
  locale: StudioFieldLocale;
  common: Record<string, string>;
  nodes: Record<string, Record<string, string>>;
}

export const STUDIO_PORT_LABEL_DICTIONARIES: Record<
  StudioFieldLocale,
  StudioPortLabelDictionary
> = {
  "en-US": {
    locale: "en-US",
    common: {},
    nodes: {},
  },
  "zh-CN": {
    locale: "zh-CN",
    common: {
      artifact: "Flow 产物",
      changed_files: "变更文件",
      context: "上下文",
      error: "错误",
      event: "事件",
      elapsedMs: "实际等待毫秒",
      acquired: "已获得",
      closed: "关闭",
      false: "条件为假",
      body: "循环体",
      body_done: "循环体完成",
      branch1: "分支 1",
      branch2: "分支 2",
      branch3: "分支 3",
      branch4: "分支 4",
      break: "跳出循环",
      batchSize: "批大小",
      available: "可用额度",
      capacity: "容量",
      checkMode: "检查时机",
      concurrency: "并发数",
      continue: "继续下一轮",
      count: "总数",
      deadlineAt: "截止时间",
      case1: "分支 1",
      case2: "分支 2",
      case3: "分支 3",
      case4: "分支 4",
      default: "默认分支",
      done: "完成",
      empty: "空集合",
      completed: "已完成",
      errors: "错误列表",
      failed: "失败",
      finalState: "最终状态",
      half_open: "半开",
      in: "输入",
      input: "输入",
      index: "索引",
      initialState: "初始状态",
      item: "当前项",
      items: "数组",
      key: "键",
      iteration: "轮次",
      values: "多路数据",
      maxed: "达到上限",
      nextState: "下一状态",
      node_specs: "节点规格",
      out: "输出",
      open: "打开",
      on_time: "准时",
      overdue: "已超时",
      overdueByMs: "超时毫秒",
      output: "输出",
      package: "生成包",
      plan: "执行计划",
      ready: "已就绪",
      ageMs: "窗口年龄毫秒",
      flushCount: "输出批次数",
      allowed: "允许",
      limited: "已限流",
      locked: "已锁定",
      response: "响应",
      remaining: "剩余额度",
      remainingMs: "剩余毫秒",
      saved: "已保存",
      loaded: "已读取",
      missing: "缺失",
      cleared: "已清除",
      snapshot: "快照",
      released: "已释放",
      replayed: "已重放",
      retryAfterMs: "重试等待毫秒",
      runId: "运行 ID",
      runRecord: "运行记录",
      rejected: "剔除项",
      result: "结果",
      results: "结果数组",
      retry: "重试",
      retryable: "可重试",
      runInput: "运行输入",
      skill_def: "Skill 定义",
      signal: "信号",
      state: "当前状态",
      status: "状态",
      startedAt: "开始时间",
      started: "已开始",
      saturated: "已满",
      summary: "摘要",
      task: "任务",
      text: "文本",
      tool_log: "工具日志",
      triggeredRuns: "触发运行数",
      true: "条件为真",
      value: "值",
      version: "版本",
      waiting: "等待中",
      received: "已收到",
      expired: "已过期",
      working_dir: "工作目录",
    },
    nodes: {
      agent: {
        task: "任务",
        context: "上下文",
        working_dir: "工作目录",
        summary: "摘要",
        changed_files: "变更文件",
        tool_log: "工具日志",
      },
      all_success: {
        results: "分支结果",
        mode: "判定模式",
        statusPath: "状态路径",
        successValues: "成功值",
        errorPath: "错误路径",
        all_success: "全部成功",
        failed: "存在失败",
        empty: "空结果",
        values: "结果数组",
        successes: "成功项",
        failures: "失败项",
        successIndexes: "成功索引",
        failureIndexes: "失败索引",
        firstSuccess: "首个成功",
        firstFailure: "首个失败",
        evaluations: "评估结果",
        summary: "摘要",
        successCount: "成功数量",
        failureCount: "失败数量",
        total: "总数",
        hasSuccess: "存在成功",
        hasFailure: "存在失败",
        successRate: "成功率",
        failureRate: "失败率",
        status: "状态",
      },
      any_success: {
        results: "分支结果",
        mode: "判定模式",
        statusPath: "状态路径",
        successValues: "成功值",
        errorPath: "错误路径",
        any_success: "任一成功",
        no_success: "无成功",
        empty: "空结果",
        values: "结果数组",
        value: "首个成功",
        successes: "成功项",
        failures: "失败项",
        successIndexes: "成功索引",
        failureIndexes: "失败索引",
        firstSuccess: "首个成功",
        firstFailure: "首个失败",
        evaluations: "评估结果",
        summary: "摘要",
        successCount: "成功数量",
        failureCount: "失败数量",
        total: "总数",
        hasSuccess: "存在成功",
        hasFailure: "存在失败",
        successRate: "成功率",
        failureRate: "失败率",
        status: "状态",
      },
      approval: {
        in: "输入",
        name: "审批名",
        mode: "审批模式",
        payload: "审批载荷",
        decision: "审批决定",
        comment: "审批意见",
        requested: "已创建",
        pending: "待审批",
        approved: "已批准",
        rejected: "已拒绝",
        cancelled: "已取消",
        expired: "已过期",
        cleared: "已清理",
        missing: "不存在",
        state: "审批状态",
        branch: "分支",
        status: "状态",
        requestFlowId: "请求 Flow ID",
        requestRunId: "请求运行 ID",
        requestNodeId: "请求节点 ID",
        title: "标题",
        assignee: "审批人",
        requestedAt: "请求时间",
        resolvedAt: "处理时间",
        expiresAt: "过期时间",
        timeoutMs: "超时毫秒",
        remainingMs: "剩余毫秒",
        stateExists: "状态是否存在",
        requestedValue: "是否已创建",
        pendingValue: "是否待审批",
        approvedValue: "是否批准",
        rejectedValue: "是否拒绝",
        cancelledValue: "是否取消",
        expiredValue: "是否过期",
        clearedValue: "是否清理",
        missingValue: "是否不存在",
      },
      audit_log: {
        in: "输入",
        name: "日志名",
        mode: "模式",
        type: "事件类型",
        actor: "操作者",
        message: "消息",
        maxEntries: "最大条数",
        limit: "读取上限",
        payload: "事件载荷",
        appended: "已记录",
        read: "已读取",
        empty: "空日志",
        cleared: "已清空",
        entries: "日志列表",
        entry: "日志条目",
        state: "日志状态",
        count: "数量",
        sequence: "序号",
      },
      compensation: {
        in: "输入",
        out: "继续",
        payload: "载荷",
        actions: "补偿动作列表",
        action: "补偿动作",
        actionName: "补偿动作名",
        name: "补偿栈名",
        mode: "模式",
        status: "状态",
        count: "动作数量",
        stackCount: "栈内数量",
        updatedAt: "更新时间",
        registeredValue: "是否注册",
        drainedValue: "是否排空",
        clearedValue: "是否清除",
        state: "补偿状态",
      },
      batch_items: {
        items: "项目列表",
        size: "批大小",
        includePartial: "包含不完整批次",
        batches: "批次列表",
        count: "批次数量",
        itemCount: "项目数量",
        hasPartial: "存在不完整批次",
      },
      batch_window: {
        in: "输入",
        name: "批窗口名",
        item: "当前项",
        mode: "模式",
        maxItems: "最大项数",
        maxAgeMs: "最大窗口年龄毫秒",
        ready: "已就绪",
        waiting: "等待更多",
        empty: "空批次",
        cleared: "已清除",
        items: "批次项",
        state: "批窗口状态",
        count: "数量",
        remaining: "剩余数量",
        ageMs: "窗口年龄毫秒",
        flushCount: "输出批次数",
      },
      branch_timeout: {
        in: "输入",
        branch: "分支结果",
        on_time: "未超时",
        timed_out: "已超时",
        unknown: "未知",
        status: "状态",
        elapsedMs: "已耗时毫秒",
        timeoutMs: "超时毫秒",
        graceMs: "宽限毫秒",
        durationMsPath: "耗时路径",
        startedAtPath: "开始时间路径",
        finishedAtPath: "完成时间路径",
        effectiveTimeoutMs: "实际超时毫秒",
        timedOut: "是否超时",
        remainingMs: "剩余毫秒",
        overdueByMs: "超时毫秒数",
      },
      cache: {
        in: "输入",
        namespace: "命名空间",
        key: "缓存键",
        value: "缓存值",
        mode: "模式",
        ttlMs: "TTL 毫秒",
        hit: "命中",
        miss: "未命中",
        stored: "已写入",
        deleted: "已删除",
        cleared: "已清空",
        expired: "已过期",
        entry: "缓存条目",
        storeKey: "存储键",
        count: "数量",
        expiresAt: "过期时间",
        remainingMs: "剩余毫秒",
      },
      code_synthesizer: {
        skill_def: "Skill 定义",
        plan: "执行计划",
        node_specs: "节点规格",
        package: "生成包",
      },
      circuit_breaker: {
        in: "输入",
        name: "熔断器名",
        closed: "关闭",
        open: "打开",
        half_open: "半开",
        state: "熔断状态",
        mode: "模式",
        status: "状态",
        circuitFlowId: "熔断 Flow ID",
        circuitRunId: "熔断运行 ID",
        circuitNodeId: "熔断节点 ID",
        failureCount: "失败次数",
        remainingMs: "剩余毫秒",
        failureThreshold: "失败阈值",
        remainingFailures: "剩余失败次数",
        resetTimeoutMs: "重置超时毫秒",
        failureWindowMs: "失败窗口毫秒",
        isOpen: "是否打开",
        isHalfOpen: "是否半开",
        isClosed: "是否关闭",
        canPass: "是否可通过",
        openedAt: "打开时间",
        lastFailureAt: "最近失败时间",
        updatedAt: "更新时间",
      },
      compare_gate: {
        in: "输入",
        left: "左值",
        right: "右值",
        matched: "已匹配",
        unmatched: "未匹配",
        operator: "操作符",
        leftPath: "左值路径",
        rightPath: "右值路径",
        rightValue: "右侧静态值",
        caseSensitive: "区分大小写",
        result: "结果",
        reason: "原因",
      },
      concat_items: {
        items: "合并项",
        sources: "来源列表",
        count: "数量",
        sourceCount: "来源数量",
      },
      checkpoint: {
        in: "输入",
        snapshot: "快照",
        saved: "已保存",
        loaded: "已读取",
        missing: "缺失",
        cleared: "已清除",
        expired: "已过期",
        state: "检查点状态",
        status: "状态",
        name: "检查点名",
        mode: "模式",
        label: "标签",
        version: "版本",
        savedAt: "保存时间",
        loadedAt: "读取时间",
        expiresAt: "过期时间",
        ttlMs: "TTL 毫秒",
        remainingMs: "剩余毫秒",
        stateExists: "状态是否存在",
        savedValue: "是否保存",
        loadedValue: "是否读取",
        missingValue: "是否缺失",
        clearedValue: "是否清除",
        expiredValue: "是否过期",
      },
      condition: {
        input: "输入",
        expression: "表达式",
        true: "条件为真",
        false: "条件为假",
        result: "条件结果",
      },
      cooldown_gate: {
        in: "输入",
        name: "冷却键名",
        now: "当前时间",
        mode: "模式",
        durationMs: "冷却时长毫秒",
        ready: "可放行",
        cooling: "冷却中",
        reset: "已重置",
        state: "冷却状态",
        status: "状态",
        remainingMs: "剩余毫秒",
        readyAt: "可放行时间",
        lastAllowedAt: "上次放行时间",
        allowedCount: "放行次数",
        suppressedCount: "抑制次数",
      },
      cron_schedule: {
        in: "输入",
        now: "当前时间",
        due: "已到期",
        not_due: "未到期",
        status: "状态",
        cron: "Cron 表达式",
        timezoneOffsetMinutes: "时区偏移分钟",
        nextAt: "下次触发时间",
        nextAtIso: "下次触发 ISO",
        waitMs: "等待毫秒",
        minute: "分钟",
        hour: "小时",
        dayOfMonth: "月内日期",
        month: "月份",
        dayOfWeek: "星期",
        dueValue: "是否到期",
        notDueValue: "是否未到期",
      },
      deadline: {
        in: "输入",
        deadlineAt: "截止时间",
        startedAt: "开始时间",
        durationMs: "持续毫秒",
        on_time: "准时",
        overdue: "已超时",
        status: "状态",
        effectiveDeadlineAt: "有效截止时间",
        graceMs: "宽限毫秒",
        remainingMs: "剩余毫秒",
        overdueByMs: "超时毫秒",
        onTimeValue: "是否准时",
        overdueValue: "是否超时",
        now: "当前时间",
      },
      dead_letter: {
        in: "输入",
        name: "死信队列名",
        mode: "模式",
        reason: "原因",
        maxItems: "最大项数",
        payload: "载荷",
        error: "错误",
        recorded: "已记录",
        drained: "已取出",
        empty: "空队列",
        cleared: "已清空",
        entries: "死信列表",
        entry: "死信条目",
        state: "死信状态",
        count: "数量",
      },
      delete_path: {
        source: "来源数据",
        deleted: "已删除",
        missing: "缺失",
        skipped: "已跳过",
        value: "更新值",
        removed: "删除值",
        exists: "原先存在",
        changed: "是否改变",
        path: "路径",
        arrayMode: "数组模式",
        reason: "原因",
      },
      delay: {
        in: "输入",
        durationMs: "等待毫秒",
        out: "完成",
        elapsedMs: "实际等待毫秒",
        startedAt: "开始时间",
        completedAt: "完成时间",
      },
      distinct_until_changed: {
        in: "输入",
        name: "状态键名",
        path: "路径",
        mode: "模式",
        emitInitial: "首次是否触发",
        value: "比较值",
        changed: "已变化",
        unchanged: "未变化",
        previous: "上次值",
        status: "状态",
        changedValue: "值是否变化",
        fingerprint: "指纹",
        evaluations: "评估次数",
        changes: "变化次数",
      },
      empty_gate: {
        in: "输入",
        mode: "模式",
        path: "路径",
        trimStrings: "是否裁剪字符串",
        value: "原始值",
        empty: "为空",
        non_empty: "非空",
        selected: "选中值",
        items: "项目列表",
        keys: "键列表",
        count: "数量",
        isEmpty: "是否为空",
        reason: "原因",
      },
      expression_eval: {
        input: "输入",
        expression: "表达式",
        result: "结果",
        truthy: "是否为真",
      },
      error_classifier: {
        error: "错误",
        matched: "已匹配",
        unmatched: "未匹配",
        code: "错误码",
        kind: "错误类型",
        category: "错误类别",
        retryable: "可重试",
        message: "错误消息",
        label: "分类标签",
        reason: "匹配原因",
      },
      fail_fast: {
        in: "输入分支",
        errors: "错误列表",
        codePath: "错误码路径",
        messagePath: "错误信息路径",
        ignoredCodes: "忽略错误码",
        failureCodes: "失败错误码",
        failed: "失败",
        clear: "无错误",
        error: "首个错误",
        ignoredErrors: "忽略错误",
        count: "错误数量",
        ignoredCount: "忽略数量",
        hasFailure: "是否失败",
        failedIndex: "失败索引",
        errorCode: "错误码",
        errorMessage: "错误信息",
        evaluations: "评估结果",
        status: "状态",
      },
      fallback: {
        in: "输入",
        value: "选中值",
        fallback: "兜底",
        error: "错误",
        mode: "模式",
        valuePath: "取值路径",
        errorPath: "错误路径",
        statusPath: "状态路径",
        successValues: "成功状态值",
        primary: "主路径",
        primaryValue: "主值",
        fallbackValue: "兜底值",
        original: "原始值",
        status: "状态",
        reason: "原因",
        usedFallback: "已用兜底",
      },
      event_trigger: {
        event: "事件",
      },
      feature_flag: {
        in: "输入",
        name: "开关名",
        mode: "模式",
        key: "灰度键",
        enabled: "已启用",
        disabled: "已禁用",
        updated: "已更新",
        cleared: "已清除",
        missing: "不存在",
        state: "开关状态",
        enabledValue: "是否启用",
        bucket: "灰度桶",
        rolloutPercent: "灰度比例",
        description: "描述",
        evaluations: "评估次数",
      },
      filter_items: {
        condition: "条件",
        items: "保留项",
        rejected: "剔除项",
        count: "保留数量",
        rejectedCount: "剔除数量",
        total: "总数量",
      },
      flatten_items: {
        items: "展平项",
        path: "路径",
        depth: "深度",
        includeNulls: "包含空值",
        count: "数量",
        inputCount: "输入数量",
      },
      first_success: {
        candidates: "候选结果",
        mode: "模式",
        valuePath: "取值路径",
        statusPath: "状态路径",
        successValues: "成功值",
        errorPath: "错误路径",
        successValueCount: "成功值数量",
        found: "已找到",
        missing: "未找到",
        value: "选中值",
        candidate: "选中候选",
        evaluations: "评估结果",
        index: "选中索引",
        count: "候选数量",
        status: "状态",
        reason: "原因",
      },
      group_items: {
        items: "分组项",
        path: "路径",
        missingKey: "缺失键",
        caseSensitive: "大小写敏感",
        sortBy: "排序方式",
        sortDirection: "排序方向",
        groups: "分组对象",
        entries: "分组列表",
        keys: "分组键",
        count: "分组数量",
        total: "总数",
      },
      for_begin: {
        body: "循环体",
        start: "起始值",
        end: "结束值",
        step: "步长",
        onError: "错误策略",
        timeoutMs: "超时毫秒",
        index: "索引",
        count: "总数",
        iterationId: "迭代 ID",
        iterationKey: "迭代定位键",
        iterationSequence: "迭代序号",
      },
      for_end: {
        body_done: "循环体完成",
        done: "完成",
        timeout: "超时",
        error: "错误",
        result: "单次结果",
        results: "结果数组",
        iterationIds: "迭代 ID 列表",
        iterationKeys: "迭代定位键列表",
        iterationSequences: "迭代序号列表",
        lastIterationId: "最后迭代 ID",
        lastIterationKey: "最后迭代定位键",
        lastIterationSequence: "最后迭代序号",
        errors: "错误列表",
        errorCount: "错误数量",
        firstError: "首个错误",
        status: "状态",
        iterationCount: "迭代次数",
        controlReason: "控制原因",
      },
      foreach_begin: {
        body: "循环体",
        items: "数组",
        mode: "执行模式",
        concurrency: "并发数",
        batchSize: "批大小",
        onError: "错误策略",
        timeoutMs: "超时毫秒",
        item: "当前项",
        index: "索引",
        count: "总数",
        iterationId: "迭代 ID",
        iterationKey: "迭代定位键",
        iterationSequence: "迭代序号",
      },
      foreach_end: {
        body_done: "循环体完成",
        done: "完成",
        timeout: "超时",
        error: "错误",
        result: "单次结果",
        results: "结果数组",
        iterationIds: "迭代 ID 列表",
        iterationKeys: "迭代定位键列表",
        iterationSequences: "迭代序号列表",
        lastIterationId: "最后迭代 ID",
        lastIterationKey: "最后迭代定位键",
        lastIterationSequence: "最后迭代序号",
        errors: "错误列表",
        errorCount: "错误数量",
        firstError: "首个错误",
        status: "状态",
        iterationCount: "迭代次数",
        controlReason: "控制原因",
      },
      flow_validator: {
        package: "生成包",
        node_specs: "节点规格",
        artifact: "Flow 产物",
      },
      http: {
        response: "响应",
      },
      idempotency_key: {
        in: "输入",
        namespace: "命名空间",
        key: "幂等键",
        value: "结果值",
        error: "错误",
        started: "首次开始",
        replayed: "重放已有结果",
        completed: "记录完成",
        failed: "记录失败",
        reset: "已重置",
        state: "幂等状态",
        status: "状态",
        stateKey: "状态键",
        mode: "模式",
        ttlMs: "TTL 毫秒",
        remainingMs: "剩余毫秒",
      },
      join: {
        in: "输入分支",
        expectedCount: "期望数量",
        out: "继续",
        values: "多路数据",
        indexedValues: "索引数据",
        presentIndexes: "有效索引",
        count: "数量",
        missingCount: "缺失数量",
        complete: "是否完整",
        empty: "是否为空",
        firstValue: "首个值",
        lastValue: "最后值",
        status: "状态",
      },
      map_items: {
        items: "映射项",
        template: "模板",
        expression: "表达式",
        usedExpression: "使用表达式",
        count: "数量",
      },
      merge: {
        in: "输入分支",
        out: "继续",
        value: "到达数据",
        values: "到达数据列表",
        count: "到达数量",
      },
      merge_object: {
        objects: "对象列表",
        mode: "模式",
        nullMode: "空值模式",
        nonObjectMode: "非对象模式",
        scalarKey: "标量键名",
        value: "合并对象",
        sources: "来源对象",
        skipped: "跳过来源",
        keys: "字段键",
        sourceCount: "来源数量",
        skippedCount: "跳过数量",
      },
      metric: {
        in: "输入",
        name: "指标名",
        mode: "模式",
        maxSamples: "最大样本数",
        value: "指标值",
        updated: "已更新",
        read: "已读取",
        reset: "已重置",
        missing: "不存在",
        state: "指标状态",
        count: "样本数",
        sum: "总和",
        min: "最小值",
        max: "最大值",
        average: "平均值",
        last: "最近值",
        samples: "最近样本",
      },
      mutex: {
        in: "输入",
        name: "锁名",
        owner: "持有者",
        acquired: "已获得",
        locked: "已锁定",
        released: "已释放",
        state: "锁状态",
        mode: "模式",
        ttlMs: "TTL 毫秒",
        remainingMs: "剩余毫秒",
        expiresAt: "过期时间",
      },
      llm: {
        result: "结果",
      },
      loop_begin: {
        body: "循环体",
        initialState: "初始状态",
        maxIterations: "最大循环次数",
        checkMode: "检查时机",
        onError: "错误策略",
        timeoutMs: "超时毫秒",
        state: "当前状态",
        iteration: "轮次",
        iterationId: "迭代 ID",
        iterationKey: "迭代定位键",
        iterationSequence: "迭代序号",
      },
      loop_break: {
        in: "输入",
        break: "跳出循环",
        reason: "原因",
        status: "状态",
        iterationId: "迭代 ID",
        iterationKey: "迭代定位键",
        iterationSequence: "迭代序号",
      },
      loop_continue: {
        in: "输入",
        continue: "继续下一轮",
        reason: "原因",
        status: "状态",
        iterationId: "迭代 ID",
        iterationKey: "迭代定位键",
        iterationSequence: "迭代序号",
      },
      loop_end: {
        body_done: "循环体完成",
        done: "完成",
        maxed: "达到上限",
        timeout: "超时",
        error: "错误",
        nextState: "下一状态",
        condition: "继续条件",
        finalState: "最终状态",
        iterationIds: "迭代 ID 列表",
        iterationKeys: "迭代定位键列表",
        iterationSequences: "迭代序号列表",
        lastIterationId: "最后迭代 ID",
        lastIterationKey: "最后迭代定位键",
        lastIterationSequence: "最后迭代序号",
        errors: "错误列表",
        errorCount: "错误数量",
        firstError: "首个错误",
        status: "状态",
        iterationCount: "迭代次数",
        controlReason: "控制原因",
      },
      node_designer: {
        skill_def: "Skill 定义",
        plan: "执行计划",
        node_specs: "节点规格",
      },
      parallel: {
        in: "输入",
        input: "输入数据",
        branch1: "分支 1",
        branch2: "分支 2",
        branch3: "分支 3",
        branch4: "分支 4",
        value: "透传数据",
        branchCount: "分支数量",
        concurrency: "并发上限",
        branchIds: "分支端口",
      },
      parse_json: {
        text: "文本",
        parsed: "已解析",
        invalid: "无效",
        value: "解析值",
        raw: "原始值",
        path: "路径",
        trim: "裁剪空白",
        unwrapCodeFence: "解包代码块",
        acceptNonString: "接受非字符串",
        status: "状态",
        type: "类型",
        errorMessage: "错误信息",
      },
      partial_success: {
        results: "分支结果",
        mode: "判定模式",
        minSuccess: "最少成功数",
        statusPath: "状态路径",
        successValues: "成功值",
        errorPath: "错误路径",
        all_success: "全部成功",
        partial: "部分成功",
        failed: "失败",
        values: "结果数组",
        successes: "成功结果",
        failures: "失败结果",
        successIndexes: "成功索引",
        failureIndexes: "失败索引",
        firstSuccess: "首个成功",
        firstFailure: "首个失败",
        evaluations: "评估结果",
        summary: "汇总",
        successCount: "成功数量",
        failureCount: "失败数量",
        total: "总数",
        remainingSuccess: "还需成功数",
        successRate: "成功率",
        status: "状态",
      },
      policy_gate: {
        in: "输入",
        input: "策略输入",
        allowed: "允许",
        denied: "拒绝",
        mode: "模式",
        rules: "规则",
        ruleCount: "规则数量",
        status: "状态",
        passed: "通过规则",
        failed: "失败规则",
        results: "规则结果",
        reason: "原因",
      },
      queue: {
        in: "输入",
        name: "队列名",
        item: "队列项",
        mode: "模式",
        maxItems: "最大项数",
        pushed: "已入队",
        popped: "已取出",
        peeked: "已查看",
        empty: "空队列",
        cleared: "已清空",
        items: "队列项列表",
        state: "队列状态",
        count: "本次数量",
        requestedCount: "请求数量",
        queueSize: "队列大小",
        remaining: "剩余容量",
      },
      quorum: {
        values: "到达值",
        met: "达到阈值",
        unmet: "未达阈值",
        indexedValues: "索引数据",
        presentIndexes: "有效索引",
        firstValue: "首个值",
        lastValue: "最后值",
        metValue: "是否达到",
        count: "到达数量",
        threshold: "阈值",
        remaining: "剩余数量",
        quorumRate: "达到比例",
        status: "状态",
      },
      race: {
        in: "输入分支",
        values: "到达值",
        winner: "胜出分支",
        empty: "空结果",
        value: "胜出值",
        indexedValues: "索引数据",
        presentIndexes: "有效索引",
        hasWinner: "存在胜出值",
        emptyValue: "是否为空",
        winnerIndex: "胜出索引",
        index: "索引",
        count: "到达数量",
        status: "状态",
      },
      rate_limit: {
        in: "输入",
        name: "限流桶名",
        allowed: "允许",
        limited: "已限流",
        state: "限流状态",
        limit: "限流上限",
        windowMs: "窗口毫秒",
        cost: "消耗额度",
        remaining: "剩余额度",
        used: "已用额度",
        retryAfterMs: "重试等待毫秒",
      },
      reduce_items: {
        items: "数组",
        mode: "模式",
        path: "路径",
        separator: "分隔符",
        result: "汇总结果",
        count: "数量",
        numericCount: "数值数量",
      },
      retry_policy: {
        error: "错误",
        idempotent: "是否幂等",
        attempt: "当前尝试",
        retry: "重试",
        exhausted: "重试耗尽",
        unsafe: "非幂等风险",
        nextAttempt: "下一次尝试",
        delayMs: "等待毫秒",
        retryable: "可重试",
        requiresIdempotency: "要求幂等",
        blockedByIdempotency: "被幂等阻止",
        status: "状态",
        maxAttempts: "最大尝试次数",
        remainingAttempts: "剩余尝试次数",
        baseDelayMs: "基础等待毫秒",
        multiplier: "退避倍数",
        maxDelayMs: "最大等待毫秒",
        jitterPercent: "抖动百分比",
        retryableOnly: "仅可重试错误",
        retryableCodes: "可重试错误码",
        requireIdempotency: "要求幂等",
        exhaustedValue: "是否耗尽",
        unsafeValue: "是否非幂等风险",
      },
      retry_state: {
        in: "输入",
        name: "重试状态名",
        error: "错误",
        idempotent: "是否幂等",
        key: "业务键",
        mode: "模式",
        retry: "重试",
        waiting: "等待重试",
        exhausted: "重试耗尽",
        unsafe: "非幂等风险",
        reset: "已重置",
        idle: "无状态",
        state: "重试状态",
        status: "状态",
        retryFlowId: "重试 Flow ID",
        retryRunId: "重试运行 ID",
        retryNodeId: "重试节点 ID",
        attempt: "当前尝试",
        nextAttempt: "下一次尝试",
        delayMs: "等待毫秒",
        retryAfterMs: "重试等待毫秒",
        nextRetryAt: "下次重试时间",
        retryable: "可重试",
        baseDelayMs: "基础等待毫秒",
        multiplier: "退避倍数",
        maxDelayMs: "最大等待毫秒",
        jitterPercent: "抖动百分比",
        retryableOnly: "仅可重试错误",
        retryableCodes: "可重试错误码",
        retryAfterMsPath: "重试等待毫秒路径",
        retryAfterAtPath: "重试等待时间路径",
        requiresIdempotency: "要求幂等",
        blockedByIdempotency: "被幂等阻止",
        stateStatus: "持久状态",
        maxAttempts: "最大尝试次数",
        remainingAttempts: "剩余尝试次数",
        exhaustedValue: "是否耗尽",
        unsafeValue: "是否非幂等风险",
        stateKey: "状态键",
      },
      resume_point: {
        in: "输入",
        snapshot: "快照",
        targetNodeId: "目标节点 ID",
        marked: "已标记",
        ready: "可恢复",
        missing: "缺失",
        cleared: "已清除",
        expired: "已过期",
        state: "恢复状态",
        name: "恢复点名",
        reason: "恢复原因",
        mode: "模式",
        status: "状态",
        stateStatus: "持久状态",
        sourceRunId: "来源运行 ID",
        version: "版本",
        markedAt: "标记时间",
        loadedAt: "读取时间",
        expiresAt: "过期时间",
        ttlMs: "TTL 毫秒",
        remainingMs: "剩余毫秒",
        stateExists: "状态是否存在",
        markedValue: "是否标记",
        readyValue: "是否可恢复",
        missingValue: "是否缺失",
        clearedValue: "是否清除",
        expiredValue: "是否过期",
      },
      rollback: {
        in: "输入",
        actions: "补偿动作",
        results: "回滚结果",
        rollback: "执行回滚",
        empty: "无动作",
        succeeded: "全部成功",
        partial: "部分成功",
        failed: "回滚失败",
        incomplete: "未完成",
        failures: "失败项",
        pending: "待处理项",
        status: "状态",
        mode: "模式",
        successPath: "成功路径",
        successValues: "成功值",
        errorPath: "错误路径",
        missingResult: "缺失结果策略",
        count: "动作数量",
        successCount: "成功数量",
        failureCount: "失败数量",
        pendingCount: "待处理数量",
        successRate: "成功率",
        failureRate: "失败率",
        pendingRate: "待处理率",
        hasFailures: "存在失败",
        hasPending: "存在待处理",
        rollbackValue: "是否执行回滚",
        emptyValue: "是否无动作",
        succeededValue: "是否全部成功",
        partialValue: "是否部分成功",
        failedValue: "是否失败",
        incompleteValue: "是否未完成",
      },
      schedule_window: {
        in: "输入",
        now: "当前时间",
        open: "窗口开启",
        closed: "窗口关闭",
        status: "状态",
        startTime: "开始时间",
        endTime: "结束时间",
        days: "开放星期",
        timezoneOffsetMinutes: "时区偏移分钟",
        day: "星期",
        minuteOfDay: "当天分钟",
        nextOpenInMs: "下次开启等待毫秒",
        nextOpenAt: "下次开启时间",
        startMinute: "开始分钟",
        endMinute: "结束分钟",
        openValue: "是否开启",
        closedValue: "是否关闭",
        overnightValue: "是否跨夜",
      },
      schema_guard: {
        in: "输入",
        input: "待校验数据",
        schema: "校验模式",
        valid: "有效",
        invalid: "无效",
        value: "原始数据",
        status: "状态",
        issues: "问题列表",
        issueCount: "问题数量",
        firstIssue: "首个问题",
      },
      schema_transform: {
        in: "输入",
        input: "来源数据",
        mappings: "映射规则",
        includeSource: "包含来源",
        requireAll: "要求全部",
        defaultValue: "默认值",
        hasDefaultValue: "有默认值",
        ruleCount: "规则数量",
        transformed: "已转换",
        missing: "缺失映射",
        value: "转换结果",
        missingMappings: "缺失映射列表",
        mappedCount: "映射数量",
        missingCount: "缺失数量",
        status: "状态",
      },
      select_path: {
        value: "数据",
        found: "已找到",
        missing: "缺失",
        source: "来源数据",
        exists: "是否存在",
        path: "路径",
        defaultValue: "默认值",
        type: "类型",
        reason: "原因",
      },
      semaphore: {
        in: "输入",
        name: "信号量名",
        owner: "持有者",
        acquired: "已获得",
        saturated: "已满",
        released: "已释放",
        state: "信号量状态",
        available: "可用额度",
        used: "已用额度",
        capacity: "容量",
        mode: "模式",
        ttlMs: "TTL 毫秒",
        remainingMs: "剩余毫秒",
      },
      set_path: {
        source: "来源数据",
        value: "更新值",
        updated: "已更新",
        missing: "缺失",
        skipped: "已跳过",
        assigned: "写入值",
        previous: "原值",
        exists: "原先存在",
        changed: "是否改变",
        path: "路径",
        createMissing: "创建缺失路径",
        overwrite: "覆盖已有值",
        reason: "原因",
      },
      slice_items: {
        items: "截取项",
        count: "数量",
        total: "总数",
        start: "起点",
        end: "终点",
        fromEnd: "从末尾开始",
        hasMore: "还有更多",
      },
      sort_items: {
        items: "排序项",
        path: "路径",
        direction: "方向",
        type: "类型",
        nulls: "空值位置",
        limit: "限制数量",
        keys: "排序键",
        first: "第一项",
        last: "最后一项",
        count: "数量",
      },
      split_text: {
        text: "文本",
        mode: "模式",
        separator: "分隔符",
        limit: "限制数量",
        trimItems: "裁剪项",
        dropEmpty: "丢弃空项",
        items: "拆分项",
        count: "数量",
        reason: "原因",
      },
      subflow: {
        in: "输入",
        input: "子流程输入",
        out: "继续",
        succeeded: "成功",
        failed: "失败",
        contract_failed: "契约失败",
        cancelled: "已取消",
        output: "子流程输出",
        runId: "子运行 ID",
        status: "子运行状态",
        runRecord: "子运行记录",
        flowId: "流程 ID",
        flowVersion: "流程版本",
        inputMode: "输入模式",
        inputValue: "输入值",
        inputSchema: "输入契约",
        outputSchema: "输出契约",
        contractMode: "契约模式",
        maxDepth: "最大深度",
        failOnError: "失败时抛错",
        localVariables: "局部变量",
        error: "子流程错误",
        contractStage: "契约阶段",
        contractIssues: "契约问题",
        contractIssueCount: "契约问题数量",
        firstContractIssue: "首个契约问题",
        childStartedAt: "子运行开始时间",
        childFinishedAt: "子运行结束时间",
        childDurationMs: "子运行耗时",
        childTraceId: "子运行 Trace ID",
        subflowDepth: "当前子流程深度",
        childDepth: "子流程调用深度",
        localVariableCount: "局部变量数量",
        localScope: "局部变量作用域",
      },
      subflow_template: {
        in: "输入",
        templateId: "模板 ID",
        templates: "模板定义",
        input: "子流程输入",
        inputMode: "输入模式",
        inputValue: "输入值",
        inputSchema: "输入契约",
        outputSchema: "输出契约",
        contractMode: "契约模式",
        maxDepth: "最大深度",
        failOnError: "失败时抛错",
        localVariables: "局部变量",
        succeeded: "成功",
        failed: "失败",
        contract_failed: "契约失败",
        cancelled: "已取消",
        missing: "缺失模板",
        output: "子流程输出",
        runId: "子运行 ID",
        status: "子运行状态",
        runRecord: "子运行记录",
        flowId: "流程 ID",
        flowVersion: "流程版本",
        contractStage: "契约阶段",
        contractIssues: "契约问题",
        contractIssueCount: "契约问题数量",
        firstContractIssue: "首个契约问题",
        childStartedAt: "子运行开始时间",
        childFinishedAt: "子运行结束时间",
        childDurationMs: "子运行耗时",
        childTraceId: "子运行 Trace ID",
        subflowDepth: "当前子流程深度",
        childDepth: "子流程调用深度",
        localVariableCount: "局部变量数量",
        localScope: "局部变量作用域",
      },
      switch_case: {
        in: "输入",
        value: "匹配数据",
        path: "路径",
        case1: "分支 1",
        case2: "分支 2",
        case3: "分支 3",
        case4: "分支 4",
        default: "默认分支",
        selected: "选中值",
        selectedText: "选中文本",
        branch: "命中分支",
      },
      stringify_json: {
        value: "数据",
        stringified: "已生成",
        failed: "失败",
        text: "JSON 文本",
        path: "路径",
        indent: "缩进",
        sortKeys: "键排序",
        bigintMode: "BigInt 模式",
        status: "状态",
        length: "长度",
        errorMessage: "错误信息",
      },
      skill_parser: {
        skill_def: "Skill 定义",
      },
      skill_planner: {
        skill_def: "Skill 定义",
        plan: "执行计划",
      },
      send_event: {
        event: "事件",
        triggeredRuns: "触发运行数",
      },
      signal_resume: {
        in: "输入",
        name: "等待状态名",
        signal: "信号",
        resumed: "已恢复",
        ignored: "已忽略",
        missing: "缺失",
        expired: "已过期",
        state: "等待状态",
        status: "状态",
        expected: "期望信号",
        stateStatus: "持久状态",
        stateExists: "状态是否存在",
        waitFlowId: "等待流程 ID",
        waitRunId: "等待运行 ID",
        waitNodeId: "等待节点 ID",
        matched: "是否匹配",
        createIfMissing: "缺失时创建",
        requestedAt: "请求时间",
        expiresAt: "过期时间",
        remainingMs: "剩余毫秒",
        resumedValue: "是否恢复",
        ignoredValue: "是否忽略",
        missingValue: "是否缺失",
        expiredValue: "是否过期",
      },
      state_get: {
        name: "状态名",
        defaultValue: "默认值",
        value: "状态值",
        found: "是否存在",
        metadata: "元数据",
      },
      state_set: {
        value: "状态值",
        previous: "原值",
        existed: "已存在",
        name: "状态名",
      },
      start: {
        runInput: "运行输入",
      },
      text_input: {
        text: "文本",
      },
      tool: {
        in: "输入",
        args: "工具参数",
        context: "上下文",
        workingDir: "工作目录",
        success: "成功",
        failed: "失败",
        result: "结果",
        ok: "是否成功",
        errorMessage: "错误信息",
        changedFiles: "变更文件",
      },
      unique_items: {
        items: "唯一项",
        path: "路径",
        keep: "保留策略",
        caseSensitive: "大小写敏感",
        duplicates: "重复项",
        keys: "唯一键",
        count: "唯一数量",
        duplicateCount: "重复数量",
      },
      window_items: {
        items: "窗口项",
        size: "窗口大小",
        step: "步长",
        includePartial: "包含不足窗口",
        windows: "窗口列表",
        ranges: "窗口范围",
        count: "窗口数量",
        itemCount: "项目数量",
        hasPartial: "存在不足窗口",
      },
      transform: {
        input: "输入",
        output: "输出",
      },
      wait_signal: {
        in: "输入",
        name: "名称",
        signal: "信号",
        received: "已收到",
        waiting: "等待中",
        expired: "已过期",
        state: "等待状态",
        status: "状态",
        expected: "期望信号",
        waitFlowId: "等待流程 ID",
        waitRunId: "等待运行 ID",
        waitNodeId: "等待节点 ID",
        requestedAt: "请求时间",
        expiresAt: "过期时间",
        timeoutMs: "超时毫秒",
        remainingMs: "剩余毫秒",
        receivedValue: "是否收到",
        waitingValue: "是否等待中",
        expiredValue: "是否过期",
      },
      wait_timer: {
        in: "输入",
        name: "名称",
        dueAt: "到期时间",
        durationMs: "等待时长毫秒",
        due: "已到期",
        waiting: "等待中",
        expired: "已过期",
        state: "计时状态",
        status: "状态",
        waitFlowId: "等待 Flow ID",
        waitRunId: "等待运行 ID",
        waitNodeId: "等待节点 ID",
        requestedAt: "请求时间",
        timeoutAt: "超时时间",
        timeoutMs: "超时毫秒",
        reset: "是否重置",
        remainingMs: "剩余毫秒",
        overdueByMs: "超时毫秒",
        dueValue: "是否到期",
        waitingValue: "是否等待中",
        expiredValue: "是否过期",
      },
    },
  },
};

export function resolvePortDisplayLabel(
  nodeType: string,
  portId: string,
  fallback: string | undefined,
  locale: StudioFieldLocale,
): string {
  const dictionary = STUDIO_PORT_LABEL_DICTIONARIES[locale];
  return (
    dictionary.nodes[nodeType]?.[portId] ??
    dictionary.common[portId] ??
    fallback ??
    portId
  );
}

export function localizePortDefinition(
  nodeType: string,
  port: PortDefinition,
  locale: StudioFieldLocale,
): PortDefinition {
  return {
    ...port,
    label: resolvePortDisplayLabel(nodeType, port.id, port.label, locale),
  };
}
