import type { PortDefinition } from "@ai-native-flow/flow-ir";
import type { StudioFieldLocale } from "./fields/fieldLabels.js";

export interface StudioPortLabelDictionary {
  locale: StudioFieldLocale;
  common: Record<string, string>;
  nodes: Record<string, Record<string, string>>;
}

export const STUDIO_PORT_LABEL_DICTIONARIES: Record<
  StudioFieldLocale,
  StudioPortLabelDictionary
> = {
  "en-US": {
    locale: "en-US",
    common: {},
    nodes: {},
  },
  "zh-CN": {
    locale: "zh-CN",
    common: {
      artifact: "Flow 产物",
      changed_files: "变更文件",
      context: "上下文",
      error: "错误",
      event: "事件",
      elapsedMs: "实际等待毫秒",
      acquired: "已获得",
      closed: "关闭",
      false: "条件为假",
      body: "循环体",
      body_done: "循环体完成",
      branch1: "分支 1",
      branch2: "分支 2",
      branch3: "分支 3",
      branch4: "分支 4",
      break: "跳出循环",
      batchSize: "批大小",
      available: "可用额度",
      capacity: "容量",
      checkMode: "检查时机",
      concurrency: "并发数",
      continue: "继续下一轮",
      count: "总数",
      deadlineAt: "截止时间",
      case1: "分支 1",
      case2: "分支 2",
      case3: "分支 3",
      case4: "分支 4",
      default: "默认分支",
      done: "完成",
      empty: "空集合",
      completed: "已完成",
      errors: "错误列表",
      failed: "失败",
      finalState: "最终状态",
      half_open: "半开",
      in: "输入",
      input: "输入",
      index: "索引",
      initialState: "初始状态",
      item: "当前项",
      items: "数组",
      key: "键",
      iteration: "轮次",
      values: "多路数据",
      maxed: "达到上限",
      nextState: "下一状态",
      node_specs: "节点规格",
      out: "输出",
      open: "打开",
      on_time: "准时",
      overdue: "已超时",
      overdueByMs: "超时毫秒",
      output: "输出",
      package: "生成包",
      plan: "执行计划",
      ready: "已就绪",
      ageMs: "窗口年龄毫秒",
      flushCount: "输出批次数",
      allowed: "允许",
      limited: "已限流",
      locked: "已锁定",
      response: "响应",
      remaining: "剩余额度",
      remainingMs: "剩余毫秒",
      saved: "已保存",
      loaded: "已读取",
      missing: "缺失",
      cleared: "已清除",
      snapshot: "快照",
      released: "已释放",
      replayed: "已重放",
      retryAfterMs: "重试等待毫秒",
      runId: "运行 ID",
      runRecord: "运行记录",
      rejected: "剔除项",
      result: "结果",
      results: "结果数组",
      retry: "重试",
      retryable: "可重试",
      runInput: "运行输入",
      skill_def: "Skill 定义",
      signal: "信号",
      state: "当前状态",
      status: "状态",
      startedAt: "开始时间",
      started: "已开始",
      saturated: "已满",
      summary: "摘要",
      task: "任务",
      text: "文本",
      tool_log: "工具日志",
      triggeredRuns: "触发运行数",
      true: "条件为真",
      value: "值",
      version: "版本",
      waiting: "等待中",
      received: "已收到",
      expired: "已过期",
      working_dir: "工作目录",
    },
    nodes: {
      agent: {
        task: "任务",
        context: "上下文",
        working_dir: "工作目录",
        summary: "摘要",
        changed_files: "变更文件",
        tool_log: "工具日志",
      },
      approval: {
        in: "输入",
        payload: "审批载荷",
        decision: "审批决定",
        comment: "审批意见",
        requested: "已创建",
        pending: "待审批",
        approved: "已批准",
        rejected: "已拒绝",
        cancelled: "已取消",
        expired: "已过期",
        cleared: "已清理",
        missing: "不存在",
        state: "审批状态",
        status: "状态",
        remainingMs: "剩余毫秒",
      },
      audit_log: {
        in: "输入",
        payload: "事件载荷",
        appended: "已记录",
        read: "已读取",
        empty: "空日志",
        cleared: "已清空",
        entries: "日志列表",
        entry: "日志条目",
        state: "日志状态",
        count: "数量",
        sequence: "序号",
      },
      compensation: {
        payload: "载荷",
        actions: "补偿动作列表",
        action: "补偿动作",
        count: "动作数量",
        state: "补偿状态",
      },
      batch_window: {
        in: "输入",
        item: "当前项",
        ready: "已就绪",
        waiting: "等待更多",
        empty: "空批次",
        cleared: "已清除",
        items: "批次项",
        state: "批窗口状态",
        count: "数量",
        remaining: "剩余数量",
        ageMs: "窗口年龄毫秒",
        flushCount: "输出批次数",
      },
      cache: {
        in: "输入",
        key: "缓存键",
        value: "缓存值",
        hit: "命中",
        miss: "未命中",
        stored: "已写入",
        deleted: "已删除",
        cleared: "已清空",
        expired: "已过期",
        entry: "缓存条目",
        namespace: "命名空间",
        count: "数量",
        expiresAt: "过期时间",
        remainingMs: "剩余毫秒",
      },
      code_synthesizer: {
        skill_def: "Skill 定义",
        plan: "执行计划",
        node_specs: "节点规格",
        package: "生成包",
      },
      circuit_breaker: {
        in: "输入",
        closed: "关闭",
        open: "打开",
        half_open: "半开",
        state: "熔断状态",
        status: "状态",
        failureCount: "失败次数",
        remainingMs: "剩余毫秒",
      },
      compare_gate: {
        in: "输入",
        left: "左值",
        right: "右值",
        matched: "已匹配",
        unmatched: "未匹配",
        operator: "操作符",
        result: "结果",
        reason: "原因",
      },
      concat_items: {
        items: "合并项",
        sources: "来源列表",
        count: "数量",
        sourceCount: "来源数量",
      },
      checkpoint: {
        in: "输入",
        snapshot: "快照",
        saved: "已保存",
        loaded: "已读取",
        missing: "缺失",
        cleared: "已清除",
        state: "检查点状态",
        status: "状态",
        version: "版本",
        remainingMs: "剩余毫秒",
      },
      condition: {
        true: "条件为真",
        false: "条件为假",
      },
      cooldown_gate: {
        in: "输入",
        now: "当前时间",
        ready: "可放行",
        cooling: "冷却中",
        reset: "已重置",
        state: "冷却状态",
        status: "状态",
        remainingMs: "剩余毫秒",
        readyAt: "可放行时间",
        lastAllowedAt: "上次放行时间",
        allowedCount: "放行次数",
        suppressedCount: "抑制次数",
      },
      deadline: {
        in: "输入",
        deadlineAt: "截止时间",
        startedAt: "开始时间",
        on_time: "准时",
        overdue: "已超时",
        status: "状态",
        remainingMs: "剩余毫秒",
        overdueByMs: "超时毫秒",
        now: "当前时间",
      },
      dead_letter: {
        in: "输入",
        payload: "载荷",
        error: "错误",
        recorded: "已记录",
        drained: "已取出",
        empty: "空队列",
        cleared: "已清空",
        entries: "死信列表",
        entry: "死信条目",
        state: "死信状态",
        count: "数量",
      },
      delete_path: {
        source: "来源数据",
        deleted: "已删除",
        missing: "缺失",
        skipped: "已跳过",
        value: "更新值",
        removed: "删除值",
        exists: "原先存在",
        changed: "是否改变",
        path: "路径",
        reason: "原因",
      },
      delay: {
        elapsedMs: "实际等待毫秒",
      },
      distinct_until_changed: {
        in: "输入",
        value: "比较值",
        changed: "已变化",
        unchanged: "未变化",
        previous: "上次值",
        status: "状态",
        changedValue: "值是否变化",
        fingerprint: "指纹",
        evaluations: "评估次数",
        changes: "变化次数",
      },
      empty_gate: {
        in: "输入",
        value: "原始值",
        empty: "为空",
        non_empty: "非空",
        selected: "选中值",
        items: "项目列表",
        keys: "键列表",
        count: "数量",
        isEmpty: "是否为空",
        reason: "原因",
      },
      error_classifier: {
        error: "错误",
        matched: "已匹配",
        unmatched: "未匹配",
        code: "错误码",
        kind: "错误类型",
        category: "错误类别",
        retryable: "可重试",
        message: "错误消息",
        label: "分类标签",
        reason: "匹配原因",
      },
      fallback: {
        in: "输入",
        value: "选中值",
        fallback: "兜底",
        error: "错误",
        primary: "主路径",
        primaryValue: "主值",
        fallbackValue: "兜底值",
        original: "原始值",
        status: "状态",
        reason: "原因",
        usedFallback: "已用兜底",
      },
      event_trigger: {
        event: "事件",
      },
      feature_flag: {
        in: "输入",
        key: "灰度键",
        enabled: "已启用",
        disabled: "已禁用",
        updated: "已更新",
        cleared: "已清除",
        missing: "不存在",
        state: "开关状态",
        enabledValue: "是否启用",
        bucket: "灰度桶",
        rolloutPercent: "灰度比例",
        evaluations: "评估次数",
      },
      filter_items: {
        items: "保留项",
        rejected: "剔除项",
        count: "保留数量",
      },
      flatten_items: {
        items: "展平项",
        count: "数量",
        inputCount: "输入数量",
      },
      first_success: {
        candidates: "候选结果",
        found: "已找到",
        missing: "未找到",
        value: "选中值",
        candidate: "选中候选",
        evaluations: "评估结果",
        index: "选中索引",
        count: "候选数量",
        status: "状态",
        reason: "原因",
      },
      group_items: {
        items: "分组项",
        groups: "分组对象",
        entries: "分组列表",
        keys: "分组键",
        count: "分组数量",
        total: "总数",
      },
      for_begin: {
        body: "循环体",
        index: "索引",
        count: "总数",
      },
      for_end: {
        body_done: "循环体完成",
        done: "完成",
        timeout: "超时",
        error: "错误",
        result: "单次结果",
        results: "结果数组",
        errors: "错误列表",
        errorCount: "错误数量",
        firstError: "首个错误",
      },
      foreach_begin: {
        body: "循环体",
        items: "数组",
        item: "当前项",
        index: "索引",
        count: "总数",
      },
      foreach_end: {
        body_done: "循环体完成",
        done: "完成",
        timeout: "超时",
        error: "错误",
        result: "单次结果",
        results: "结果数组",
        errors: "错误列表",
        errorCount: "错误数量",
        firstError: "首个错误",
      },
      flow_validator: {
        package: "生成包",
        node_specs: "节点规格",
        artifact: "Flow 产物",
      },
      http: {
        response: "响应",
      },
      idempotency_key: {
        in: "输入",
        key: "幂等键",
        value: "结果值",
        error: "错误",
        started: "首次开始",
        replayed: "重放已有结果",
        completed: "记录完成",
        failed: "记录失败",
        reset: "已重置",
        state: "幂等状态",
        status: "状态",
        remainingMs: "剩余毫秒",
      },
      join: {
        in: "输入分支",
        out: "继续",
        values: "多路数据",
        count: "数量",
      },
      map_items: {
        items: "映射项",
        count: "数量",
      },
      merge: {
        in: "输入分支",
        out: "继续",
        value: "到达数据",
        values: "到达数据列表",
        count: "到达数量",
      },
      merge_object: {
        objects: "对象列表",
        value: "合并对象",
        sources: "来源对象",
        skipped: "跳过来源",
        keys: "字段键",
        sourceCount: "来源数量",
        skippedCount: "跳过数量",
      },
      metric: {
        in: "输入",
        value: "指标值",
        updated: "已更新",
        read: "已读取",
        reset: "已重置",
        missing: "不存在",
        state: "指标状态",
        count: "样本数",
        sum: "总和",
        min: "最小值",
        max: "最大值",
        average: "平均值",
        last: "最近值",
        samples: "最近样本",
      },
      mutex: {
        in: "输入",
        owner: "持有者",
        acquired: "已获得",
        locked: "已锁定",
        released: "已释放",
        state: "锁状态",
        remainingMs: "剩余毫秒",
        expiresAt: "过期时间",
      },
      llm: {
        result: "结果",
      },
      loop_begin: {
        body: "循环体",
        initialState: "初始状态",
        state: "当前状态",
        iteration: "轮次",
      },
      loop_break: {
        break: "跳出循环",
      },
      loop_continue: {
        continue: "继续下一轮",
      },
      loop_end: {
        body_done: "循环体完成",
        done: "完成",
        maxed: "达到上限",
        timeout: "超时",
        error: "错误",
        nextState: "下一状态",
        finalState: "最终状态",
        errors: "错误列表",
        errorCount: "错误数量",
        firstError: "首个错误",
      },
      node_designer: {
        skill_def: "Skill 定义",
        plan: "执行计划",
        node_specs: "节点规格",
      },
      parallel: {
        in: "输入",
        input: "输入数据",
        branch1: "分支 1",
        branch2: "分支 2",
        branch3: "分支 3",
        branch4: "分支 4",
        value: "透传数据",
      },
      parse_json: {
        text: "文本",
        parsed: "已解析",
        invalid: "无效",
        value: "解析值",
        raw: "原始值",
        status: "状态",
        type: "类型",
        errorMessage: "错误信息",
      },
      policy_gate: {
        in: "输入",
        input: "策略输入",
        allowed: "允许",
        denied: "拒绝",
        status: "状态",
        passed: "通过规则",
        failed: "失败规则",
        results: "规则结果",
        reason: "原因",
      },
      queue: {
        in: "输入",
        item: "队列项",
        pushed: "已入队",
        popped: "已取出",
        peeked: "已查看",
        empty: "空队列",
        cleared: "已清空",
        items: "队列项列表",
        state: "队列状态",
        count: "本次数量",
        queueSize: "队列大小",
        remaining: "剩余容量",
      },
      quorum: {
        values: "到达值",
        met: "达到阈值",
        unmet: "未达阈值",
        count: "到达数量",
        threshold: "阈值",
        remaining: "剩余数量",
        status: "状态",
      },
      rate_limit: {
        in: "输入",
        allowed: "允许",
        limited: "已限流",
        state: "限流状态",
        remaining: "剩余额度",
        used: "已用额度",
        retryAfterMs: "重试等待毫秒",
      },
      reduce_items: {
        items: "数组",
        result: "汇总结果",
        count: "数量",
      },
      retry_policy: {
        error: "错误",
        attempt: "当前尝试",
        retry: "重试",
        exhausted: "重试耗尽",
        nextAttempt: "下一次尝试",
        delayMs: "等待毫秒",
        retryable: "可重试",
      },
      resume_point: {
        in: "输入",
        snapshot: "快照",
        targetNodeId: "目标节点 ID",
        marked: "已标记",
        ready: "可恢复",
        missing: "缺失",
        cleared: "已清除",
        expired: "已过期",
        state: "恢复状态",
        reason: "恢复原因",
        status: "状态",
        version: "版本",
        remainingMs: "剩余毫秒",
      },
      rollback: {
        in: "输入",
        actions: "补偿动作",
        results: "回滚结果",
        rollback: "执行回滚",
        empty: "无动作",
        succeeded: "全部成功",
        partial: "部分成功",
        failed: "回滚失败",
        failures: "失败项",
        pending: "待处理项",
        status: "状态",
        count: "动作数量",
        successCount: "成功数量",
        failureCount: "失败数量",
        pendingCount: "待处理数量",
      },
      schedule_window: {
        in: "输入",
        now: "当前时间",
        open: "窗口开启",
        closed: "窗口关闭",
        status: "状态",
        day: "星期",
        minuteOfDay: "当天分钟",
        nextOpenInMs: "下次开启等待毫秒",
        startMinute: "开始分钟",
        endMinute: "结束分钟",
      },
      schema_guard: {
        in: "输入",
        input: "待校验数据",
        valid: "有效",
        invalid: "无效",
        value: "原始数据",
        status: "状态",
        issues: "问题列表",
        issueCount: "问题数量",
        firstIssue: "首个问题",
      },
      select_path: {
        value: "数据",
        found: "已找到",
        missing: "缺失",
        source: "来源数据",
        exists: "是否存在",
        path: "路径",
        type: "类型",
        reason: "原因",
      },
      semaphore: {
        in: "输入",
        owner: "持有者",
        acquired: "已获得",
        saturated: "已满",
        released: "已释放",
        state: "信号量状态",
        available: "可用额度",
        used: "已用额度",
        capacity: "容量",
        remainingMs: "剩余毫秒",
      },
      set_path: {
        source: "来源数据",
        value: "更新值",
        updated: "已更新",
        missing: "缺失",
        skipped: "已跳过",
        assigned: "写入值",
        previous: "原值",
        exists: "原先存在",
        changed: "是否改变",
        path: "路径",
        reason: "原因",
      },
      slice_items: {
        items: "截取项",
        count: "数量",
        total: "总数",
        start: "起点",
        end: "终点",
        hasMore: "还有更多",
      },
      sort_items: {
        items: "排序项",
        keys: "排序键",
        first: "第一项",
        last: "最后一项",
        count: "数量",
      },
      split_text: {
        text: "文本",
        items: "拆分项",
        count: "数量",
        reason: "原因",
      },
      subflow: {
        in: "输入",
        input: "子流程输入",
        out: "继续",
        succeeded: "成功",
        failed: "失败",
        contract_failed: "契约失败",
        cancelled: "已取消",
        output: "子流程输出",
        runId: "子运行 ID",
        status: "子运行状态",
        runRecord: "子运行记录",
        error: "子流程错误",
        contractStage: "契约阶段",
        contractIssues: "契约问题",
        contractIssueCount: "契约问题数量",
        firstContractIssue: "首个契约问题",
        subflowDepth: "当前子流程深度",
        childDepth: "子流程调用深度",
        localVariableCount: "局部变量数量",
        localScope: "局部变量作用域",
      },
      subflow_template: {
        in: "输入",
        templateId: "模板 ID",
        input: "子流程输入",
        succeeded: "成功",
        failed: "失败",
        cancelled: "已取消",
        missing: "缺失模板",
        output: "子流程输出",
        runId: "子运行 ID",
        status: "子运行状态",
        runRecord: "子运行记录",
        flowId: "流程 ID",
        flowVersion: "流程版本",
      },
      switch_case: {
        in: "输入",
        value: "匹配数据",
        case1: "分支 1",
        case2: "分支 2",
        case3: "分支 3",
        case4: "分支 4",
        default: "默认分支",
      },
      stringify_json: {
        value: "数据",
        stringified: "已生成",
        failed: "失败",
        text: "JSON 文本",
        status: "状态",
        length: "长度",
        errorMessage: "错误信息",
      },
      skill_parser: {
        skill_def: "Skill 定义",
      },
      skill_planner: {
        skill_def: "Skill 定义",
        plan: "执行计划",
      },
      send_event: {
        event: "事件",
        triggeredRuns: "触发运行数",
      },
      signal_resume: {
        in: "输入",
        name: "等待状态名",
        signal: "信号",
        resumed: "已恢复",
        ignored: "已忽略",
        missing: "缺失",
        expired: "已过期",
        state: "等待状态",
        status: "状态",
        expected: "期望信号",
      },
      state_get: {
        name: "状态名",
        value: "状态值",
        found: "是否存在",
        metadata: "元数据",
      },
      state_set: {
        value: "状态值",
        previous: "原值",
        existed: "已存在",
        name: "状态名",
      },
      start: {
        runInput: "运行输入",
      },
      text_input: {
        text: "文本",
      },
      tool: {
        result: "结果",
      },
      unique_items: {
        items: "唯一项",
        duplicates: "重复项",
        keys: "唯一键",
        count: "唯一数量",
        duplicateCount: "重复数量",
      },
      window_items: {
        items: "窗口项",
        windows: "窗口列表",
        ranges: "窗口范围",
        count: "窗口数量",
        itemCount: "项目数量",
        hasPartial: "存在不足窗口",
      },
      transform: {
        input: "输入",
        output: "输出",
      },
      wait_signal: {
        in: "输入",
        signal: "信号",
        received: "已收到",
        waiting: "等待中",
        expired: "已过期",
        state: "等待状态",
        status: "状态",
        remainingMs: "剩余毫秒",
      },
      wait_timer: {
        in: "输入",
        dueAt: "到期时间",
        durationMs: "等待时长毫秒",
        due: "已到期",
        waiting: "等待中",
        expired: "已过期",
        state: "计时状态",
        status: "状态",
        remainingMs: "剩余毫秒",
        overdueByMs: "超时毫秒",
      },
    },
  },
};

export function resolvePortDisplayLabel(
  nodeType: string,
  portId: string,
  fallback: string | undefined,
  locale: StudioFieldLocale,
): string {
  const dictionary = STUDIO_PORT_LABEL_DICTIONARIES[locale];
  return (
    dictionary.nodes[nodeType]?.[portId] ??
    dictionary.common[portId] ??
    fallback ??
    portId
  );
}

export function localizePortDefinition(
  nodeType: string,
  port: PortDefinition,
  locale: StudioFieldLocale,
): PortDefinition {
  return {
    ...port,
    label: resolvePortDisplayLabel(nodeType, port.id, port.label, locale),
  };
}
