import type { PortDefinition } from "@ai-native-flow/flow-ir";
import type { StudioFieldLocale } from "./fields/fieldLabels.js";

export interface StudioPortLabelDictionary {
  locale: StudioFieldLocale;
  common: Record<string, string>;
  nodes: Record<string, Record<string, string>>;
}

export const STUDIO_PORT_LABEL_DICTIONARIES: Record<
  StudioFieldLocale,
  StudioPortLabelDictionary
> = {
  "en-US": {
    locale: "en-US",
    common: {},
    nodes: {},
  },
  "zh-CN": {
    locale: "zh-CN",
    common: {
      artifact: "Flow 产物",
      changed_files: "变更文件",
      context: "上下文",
      error: "错误",
      event: "事件",
      elapsedMs: "实际等待毫秒",
      acquired: "已获得",
      closed: "关闭",
      false: "条件为假",
      body: "循环体",
      body_done: "循环体完成",
      branch1: "分支 1",
      branch2: "分支 2",
      branch3: "分支 3",
      branch4: "分支 4",
      break: "跳出循环",
      batchSize: "批大小",
      available: "可用额度",
      capacity: "容量",
      checkMode: "检查时机",
      concurrency: "并发数",
      continue: "继续下一轮",
      count: "总数",
      deadlineAt: "截止时间",
      case1: "分支 1",
      case2: "分支 2",
      case3: "分支 3",
      case4: "分支 4",
      default: "默认分支",
      done: "完成",
      empty: "空集合",
      completed: "已完成",
      errors: "错误列表",
      failed: "失败",
      finalState: "最终状态",
      half_open: "半开",
      in: "输入",
      input: "输入",
      index: "索引",
      initialState: "初始状态",
      item: "当前项",
      items: "数组",
      key: "键",
      iteration: "轮次",
      values: "多路数据",
      maxed: "达到上限",
      nextState: "下一状态",
      node_specs: "节点规格",
      out: "输出",
      open: "打开",
      on_time: "准时",
      overdue: "已超时",
      overdueByMs: "超时毫秒",
      output: "输出",
      package: "生成包",
      plan: "执行计划",
      allowed: "允许",
      limited: "已限流",
      locked: "已锁定",
      response: "响应",
      remaining: "剩余额度",
      remainingMs: "剩余毫秒",
      saved: "已保存",
      loaded: "已读取",
      missing: "缺失",
      cleared: "已清除",
      snapshot: "快照",
      released: "已释放",
      replayed: "已重放",
      retryAfterMs: "重试等待毫秒",
      runId: "运行 ID",
      runRecord: "运行记录",
      rejected: "剔除项",
      result: "结果",
      results: "结果数组",
      retry: "重试",
      retryable: "可重试",
      runInput: "运行输入",
      skill_def: "Skill 定义",
      signal: "信号",
      state: "当前状态",
      status: "状态",
      startedAt: "开始时间",
      started: "已开始",
      saturated: "已满",
      summary: "摘要",
      task: "任务",
      text: "文本",
      tool_log: "工具日志",
      triggeredRuns: "触发运行数",
      true: "条件为真",
      value: "值",
      version: "版本",
      waiting: "等待中",
      received: "已收到",
      expired: "已过期",
      working_dir: "工作目录",
    },
    nodes: {
      agent: {
        task: "任务",
        context: "上下文",
        working_dir: "工作目录",
        summary: "摘要",
        changed_files: "变更文件",
        tool_log: "工具日志",
      },
      compensation: {
        payload: "载荷",
        actions: "补偿动作列表",
        action: "补偿动作",
        count: "动作数量",
        state: "补偿状态",
      },
      code_synthesizer: {
        skill_def: "Skill 定义",
        plan: "执行计划",
        node_specs: "节点规格",
        package: "生成包",
      },
      circuit_breaker: {
        in: "输入",
        closed: "关闭",
        open: "打开",
        half_open: "半开",
        state: "熔断状态",
        status: "状态",
        failureCount: "失败次数",
        remainingMs: "剩余毫秒",
      },
      checkpoint: {
        in: "输入",
        snapshot: "快照",
        saved: "已保存",
        loaded: "已读取",
        missing: "缺失",
        cleared: "已清除",
        state: "检查点状态",
        status: "状态",
        version: "版本",
        remainingMs: "剩余毫秒",
      },
      condition: {
        true: "条件为真",
        false: "条件为假",
      },
      deadline: {
        in: "输入",
        deadlineAt: "截止时间",
        startedAt: "开始时间",
        on_time: "准时",
        overdue: "已超时",
        status: "状态",
        remainingMs: "剩余毫秒",
        overdueByMs: "超时毫秒",
        now: "当前时间",
      },
      delay: {
        elapsedMs: "实际等待毫秒",
      },
      event_trigger: {
        event: "事件",
      },
      filter_items: {
        items: "保留项",
        rejected: "剔除项",
        count: "保留数量",
      },
      for_begin: {
        body: "循环体",
        index: "索引",
        count: "总数",
      },
      for_end: {
        body_done: "循环体完成",
        done: "完成",
        result: "单次结果",
        results: "结果数组",
      },
      foreach_begin: {
        body: "循环体",
        items: "数组",
        item: "当前项",
        index: "索引",
        count: "总数",
      },
      foreach_end: {
        body_done: "循环体完成",
        done: "完成",
        result: "单次结果",
        results: "结果数组",
        errors: "错误列表",
      },
      flow_validator: {
        package: "生成包",
        node_specs: "节点规格",
        artifact: "Flow 产物",
      },
      http: {
        response: "响应",
      },
      idempotency_key: {
        in: "输入",
        key: "幂等键",
        value: "结果值",
        error: "错误",
        started: "首次开始",
        replayed: "重放已有结果",
        completed: "记录完成",
        failed: "记录失败",
        reset: "已重置",
        state: "幂等状态",
        status: "状态",
        remainingMs: "剩余毫秒",
      },
      join: {
        in: "输入分支",
        out: "继续",
        values: "多路数据",
        count: "数量",
      },
      map_items: {
        items: "映射项",
        count: "数量",
      },
      merge: {
        in: "输入分支",
        out: "继续",
        value: "到达数据",
        values: "到达数据列表",
        count: "到达数量",
      },
      mutex: {
        in: "输入",
        owner: "持有者",
        acquired: "已获得",
        locked: "已锁定",
        released: "已释放",
        state: "锁状态",
        remainingMs: "剩余毫秒",
        expiresAt: "过期时间",
      },
      llm: {
        result: "结果",
      },
      loop_begin: {
        body: "循环体",
        initialState: "初始状态",
        state: "当前状态",
        iteration: "轮次",
      },
      loop_break: {
        break: "跳出循环",
      },
      loop_continue: {
        continue: "继续下一轮",
      },
      loop_end: {
        body_done: "循环体完成",
        done: "完成",
        maxed: "达到上限",
        nextState: "下一状态",
        finalState: "最终状态",
      },
      node_designer: {
        skill_def: "Skill 定义",
        plan: "执行计划",
        node_specs: "节点规格",
      },
      parallel: {
        in: "输入",
        input: "输入数据",
        branch1: "分支 1",
        branch2: "分支 2",
        branch3: "分支 3",
        branch4: "分支 4",
        value: "透传数据",
      },
      rate_limit: {
        in: "输入",
        allowed: "允许",
        limited: "已限流",
        state: "限流状态",
        remaining: "剩余额度",
        used: "已用额度",
        retryAfterMs: "重试等待毫秒",
      },
      reduce_items: {
        items: "数组",
        result: "汇总结果",
        count: "数量",
      },
      retry_policy: {
        error: "错误",
        attempt: "当前尝试",
        retry: "重试",
        exhausted: "重试耗尽",
        nextAttempt: "下一次尝试",
        delayMs: "等待毫秒",
        retryable: "可重试",
      },
      semaphore: {
        in: "输入",
        owner: "持有者",
        acquired: "已获得",
        saturated: "已满",
        released: "已释放",
        state: "信号量状态",
        available: "可用额度",
        used: "已用额度",
        capacity: "容量",
        remainingMs: "剩余毫秒",
      },
      subflow: {
        in: "输入",
        input: "子流程输入",
        out: "继续",
        succeeded: "成功",
        failed: "失败",
        cancelled: "已取消",
        output: "子流程输出",
        runId: "子运行 ID",
        status: "子运行状态",
        runRecord: "子运行记录",
        error: "子流程错误",
      },
      switch_case: {
        in: "输入",
        value: "匹配数据",
        case1: "分支 1",
        case2: "分支 2",
        case3: "分支 3",
        case4: "分支 4",
        default: "默认分支",
      },
      skill_parser: {
        skill_def: "Skill 定义",
      },
      skill_planner: {
        skill_def: "Skill 定义",
        plan: "执行计划",
      },
      send_event: {
        event: "事件",
        triggeredRuns: "触发运行数",
      },
      state_get: {
        name: "状态名",
        value: "状态值",
        found: "是否存在",
        metadata: "元数据",
      },
      state_set: {
        value: "状态值",
        previous: "原值",
        existed: "已存在",
        name: "状态名",
      },
      start: {
        runInput: "运行输入",
      },
      text_input: {
        text: "文本",
      },
      tool: {
        result: "结果",
      },
      transform: {
        input: "输入",
        output: "输出",
      },
      wait_signal: {
        in: "输入",
        signal: "信号",
        received: "已收到",
        waiting: "等待中",
        expired: "已过期",
        state: "等待状态",
        status: "状态",
        remainingMs: "剩余毫秒",
      },
    },
  },
};

export function resolvePortDisplayLabel(
  nodeType: string,
  portId: string,
  fallback: string | undefined,
  locale: StudioFieldLocale,
): string {
  const dictionary = STUDIO_PORT_LABEL_DICTIONARIES[locale];
  return (
    dictionary.nodes[nodeType]?.[portId] ??
    dictionary.common[portId] ??
    fallback ??
    portId
  );
}

export function localizePortDefinition(
  nodeType: string,
  port: PortDefinition,
  locale: StudioFieldLocale,
): PortDefinition {
  return {
    ...port,
    label: resolvePortDisplayLabel(nodeType, port.id, port.label, locale),
  };
}
