/**
 * `code_synthesizer` - third LLM stage + deterministic flow assembly.
 *
 * For every NodeSpec we ask the LLM to synthesise a self-contained
 * `defineNode(...)` TypeScript module. Calls run in parallel (bounded
 * by `max_concurrency`) and each response is validated as a strict
 * `{ filePath, source }` object.
 *
 * The flow JSON itself is NOT generated by the model - that would be
 * needlessly risky. Instead we:
 *
 *  1. Build a NodeTypeRegistry whose entries mirror the NodeSpec
 *     port shapes.
 *  2. Use the project's own `defineFlow` builder to wire the nodes
 *     according to `plan.steps[*].dependencies`, matching upstream
 *     output port ids against downstream input port ids by name.
 *  3. Deterministically dump the FlowGraph and bundle it alongside
 *     the synthesised TypeScript files into a `GeneratedFlowPackage`.
 *
 * The package also includes a `_llm.ts` helper (when any node uses
 * `llm_prompt` strategy), a `nodes/index.ts`, a `build.ts`, a
 * `runtime.ts` and a README - the complete shape that the existing
 * `apps/code-review-iwiki` package uses, so the consumer can drop the
 * artefact into `apps/<skill-name>/` and it just runs.
 */

import { defineNode } from "@ai-native-flow/node-sdk";
import {
  DEFAULT_LLM_API_KEY_REF,
  DEFAULT_LLM_BASE_URL_REF,
  DEFAULT_LLM_MAX_TOKENS,
  DEFAULT_LLM_MODEL_REF,
  DEFAULT_LLM_TEMPERATURE,
} from "@ai-native-flow/runtime";
import { z } from "zod";

import {
  defineFlow,
  type FlowBuilder,
} from "@ai-native-flow/flow-builder";
import {
  createDefaultRegistry,
  type NodeTypeDefinition,
} from "@ai-native-flow/flow-ir";
import { getBuiltinNodeDefinitions } from "@ai-native-flow/runtime";

import { chatJson, runWithConcurrency } from "./_llm.js";
import {
  type ExecutionPlan,
  type GeneratedFile,
  type GeneratedFlowPackage,
  type NodeSpec,
  type SkillDefinition,
  type SkillRequirements,
  skillRequirementsSchema,
} from "./types.js";

/* -------------------------------------------------------------------------- */
/* config                                                                     */
/* -------------------------------------------------------------------------- */

const codeSynthesizerConfig = z
  .object({
    /** Per-call base URL; may be a `$var:NAME` reference. */
    base_url: z.string().min(1).default(DEFAULT_LLM_BASE_URL_REF),
    /** Per-call bearer token; may be a `$var:NAME` reference. */
    api_key: z.string().min(1).default(DEFAULT_LLM_API_KEY_REF),
    /** Per-call model id; may be a `$var:NAME` reference. */
    model: z.string().min(1).default(DEFAULT_LLM_MODEL_REF),
    temperature: z.number().min(0).max(2).default(DEFAULT_LLM_TEMPERATURE),
    max_tokens: z.number().int().min(1).max(32_000).default(DEFAULT_LLM_MAX_TOKENS),
    max_concurrency: z.number().int().min(1).max(16).default(3),
    max_retries: z.number().int().min(0).default(2),
    package_scope: z.string().default("@ai-native-flow"),
    flow_version: z.string().default("1.0.0"),
  })
  .passthrough();
type CodeSynthesizerConfig = z.infer<typeof codeSynthesizerConfig>;

/* -------------------------------------------------------------------------- */
/* response schema (per LLM call)                                             */
/* -------------------------------------------------------------------------- */

const synthesisedNodeSchema = z.object({
  filePath: z
    .string()
    .min(1)
    .regex(/\.ts$/, "filePath must end with .ts"),
  source: z.string().min(1),
});

/* -------------------------------------------------------------------------- */
/* node                                                                       */
/* -------------------------------------------------------------------------- */

export const codeSynthesizerNode = defineNode({
  type: "code_synthesizer",
  typeVersion: "1.0.0",
  title: "Code Synthesizer (LLM parallel)",
  description:
    "Synthesize compilable defineNode TypeScript source for each NodeSpec, then assemble the FlowGraph, build.ts, and runtime.ts deterministically.",
  capabilities: {
    requiredPermissions: ["network.http", "secret.read"],
  },
  config: codeSynthesizerConfig,
  fieldMeta: {
    base_url: {
      label: "URL",
      placeholder: DEFAULT_LLM_BASE_URL_REF,
      order: 1,
    },
    api_key: {
      label: "APIKEY",
      placeholder: DEFAULT_LLM_API_KEY_REF,
      secret: true,
      order: 2,
    },
    model: { label: "Model", placeholder: DEFAULT_LLM_MODEL_REF, order: 3 },
    temperature: { label: "Temperature", order: 4 },
    max_tokens: { label: "Max Tokens", order: 5 },
    max_concurrency: { label: "Max concurrency", order: 6 },
    max_retries: { label: "JSON retry count", order: 7 },
    package_scope: { label: "Generated package scope", order: 8 },
    flow_version: { label: "Flow version", order: 9 },
  },
  ports: [
    { id: "skill_def", direction: "input", kind: "data", label: "SkillDefinition" },
    { id: "plan", direction: "input", kind: "data", label: "ExecutionPlan" },
    { id: "node_specs", direction: "input", kind: "data", label: "NodeSpec[]" },
    {
      id: "package",
      direction: "output",
      kind: "data",
      label: "GeneratedFlowPackage",
      schema: { type: "object" },
    },
  ],
  validateInput: false,
  async run({ input, config, ctx }) {
    const cfg = config as CodeSynthesizerConfig;
    const raw = input as Record<string, unknown>;
    const skill = raw.skill_def as SkillDefinition | undefined;
    const plan = raw.plan as ExecutionPlan | undefined;
    const specs = (raw.node_specs ?? []) as NodeSpec[];

    if (!skill || !plan || !Array.isArray(specs) || specs.length === 0) {
      return {
        kind: "error",
        error: {
          code: "node.code_synthesizer.missing_input",
          message:
            "code_synthesizer needs all of `skill_def`, `plan` and `node_specs`.",
          kind: "validation",
          category: "author",
        },
      };
    }

    const specError = validateSynthesizerSpecs(specs);
    if (specError) {
      return {
        kind: "error",
        error: {
          code: "node.code_synthesizer.invalid_node_specs",
          message: `code_synthesizer: ${specError}`,
          kind: "validation",
          category: "author",
        },
      };
    }

    const logger = {
      info: (m: string, d?: Record<string, unknown>) => ctx.log.info(m, d),
      warn: (m: string, d?: Record<string, unknown>) => ctx.log.warn(m, d),
    };

    /* ---------- 1. LLM-synthesise each node module ------------------------ */
    const system = buildSystemPrompt();
    let nodeFiles: Array<{ spec: NodeSpec; file: GeneratedFile }>;
    try {
      const synthesised = await runWithConcurrency(
        specs,
        cfg.max_concurrency,
        async (spec, idx) => {
          ctx.log.info(
            `code_synthesizer: synthesising ${idx + 1}/${specs.length}`,
            { nodeType: spec.nodeType },
          );
          const step = plan.steps.find((s) => s.id === spec.stepId);
          const user = buildUserPrompt(skill, plan, spec, step);
          const result = await chatJson({
            system,
            user,
            schema: synthesisedNodeSchema,
            baseUrl: cfg.base_url || undefined,
            apiKey: cfg.api_key || undefined,
            model: cfg.model || undefined,
            temperature: cfg.temperature,
            maxTokens: cfg.max_tokens,
            maxRetries: cfg.max_retries,
            signal: ctx.signal,
            ctx,
            logger,
          });
          // Force the path into a predictable location regardless of
          // what the model picked. Filenames are camelCase by convention.
          const safePath = `nodes/${toCamelCase(spec.nodeType)}.ts`;
          return {
            spec,
            file: {
              path: safePath,
              contents: ensureSourceMentionsType(result.source, spec.nodeType),
            } satisfies GeneratedFile,
          };
        },
      );
      nodeFiles = synthesised;
    } catch (cause) {
      return {
        kind: "error",
        error: {
          code: "node.code_synthesizer.llm_failed",
          message: `code_synthesizer: ${(cause as Error).message}`,
          kind: "external",
          category: "external",
        },
      };
    }

    /* ---------- 2. Deterministically assemble the FlowGraph -------------- */
    let flowJson: string;
    let flowGraph: unknown;
    try {
      const built = assembleFlowGraph(skill, plan, specs, cfg.flow_version);
      flowJson = built.json;
      flowGraph = built.graph;
    } catch (cause) {
      return {
        kind: "error",
        error: {
          code: "node.code_synthesizer.assembly_failed",
          message: `code_synthesizer: flow assembly failed: ${(cause as Error).message}`,
          kind: "validation",
          category: "author",
        },
      };
    }

    /* ---------- 3. Render boilerplate (rule-based, not LLM) -------------- */
    const flowId = sanitizeFlowId(skill.name);
    const requiresLlm = specs.some((s) => s.requiresLlm);

    const files: GeneratedFile[] = nodeFiles.map((nf) => nf.file);
    if (requiresLlm) {
      files.push({ path: "nodes/_llm.ts", contents: BUNDLED_LLM_TS });
    }

    const nodesIndex: GeneratedFile = {
      path: "nodes/index.ts",
      contents: renderNodesIndex(skill.name, specs),
    };
    const buildScript: GeneratedFile = {
      path: "build.ts",
      contents: renderBuildTs(skill, flowId, cfg.flow_version, specs),
    };
    const runtimeScript: GeneratedFile = {
      path: "runtime.ts",
      contents: renderRuntimeTs(skill, flowId, cfg.flow_version, specs),
    };
    const cliScript: GeneratedFile = {
      path: "cli.ts",
      contents: renderCliTs(flowId),
    };
    const packageJson: GeneratedFile = {
      path: "package.json",
      contents: renderPackageJson(skill, flowId),
    };
    const tsconfig: GeneratedFile = {
      path: "tsconfig.json",
      contents: renderTsconfigJson(),
    };
    const flowJsonFile: GeneratedFile = {
      path: `flows/${flowId}.json`,
      contents: `${flowJson}\n`,
    };
    const readme: GeneratedFile = {
      path: "README.md",
      contents: renderReadme(skill, plan, specs, flowId),
    };

    const pkg: GeneratedFlowPackage = {
      skillName: skill.name,
      flowId,
      flowVersion: cfg.flow_version,
      requirements: normalizePackageRequirements(plan),
      files,
      nodesIndex,
      buildScript,
      runtimeScript,
      cliScript,
      packageJson,
      tsconfig,
      flowJsonFile,
      flowGraph,
      readme,
    };

    ctx.log.info("code_synthesizer: package ready", {
      skillName: skill.name,
      flowId,
      nodeCount: specs.length,
      fileCount: files.length + 8, // + index/build/runtime/cli/package/tsconfig/flowJson/readme
      requiresLlm,
    });

    return {
      kind: "success",
      outputs: { out: null, package: pkg },
    };
  },
});

/* -------------------------------------------------------------------------- */
/* prompts                                                                    */
/* -------------------------------------------------------------------------- */

function buildSystemPrompt(): string {
  return [
    "You are a senior TypeScript engineer for the AI Native Flow project.",
    "Given a NodeSpec produced by the previous designer stage, write a",
    "single self-contained TypeScript module that defines exactly one",
    "node via `defineNode` from `@ai-native-flow/node-sdk`.",
    "",
    "OUTPUT CONTRACT - return ONE JSON object, no prose, no fences:",
    "",
    `{ "filePath": "nodes/<nodeTypeCamel>.ts", "source": "<full ts source>" }`,
    "",
    "STRICT REQUIREMENTS for the source:",
    "  - ESM TypeScript with `.js` import suffixes (the project compiles",
    "    with NodeNext / ESM).",
    "  - Import `defineNode` from `@ai-native-flow/node-sdk`.",
    "  - Import `z` from `zod`.",
    "  - Define a zod config schema matching `nodeSpec.configFields`",
    "    (use `.passthrough()` so the runtime can pass extra keys).",
    `    For "llm_prompt" nodes you MUST additionally declare these`,
    `    OAI-compatible fields first, in this exact order, and keep them required:`,
    `        base_url: z.string().min(1).default("$var:LLM_BASE_URL"),`,
    `        api_key:  z.string().min(1).default("$var:LLM_API_KEY"),`,
    `        model:    z.string().min(1).default("$var:LLM_DEFAULT_MODEL"),`,
    `    Then declare temperature and max_tokens with practical defaults:`,
    `        temperature: z.number().min(0).max(2).default(0),`,
    `        max_tokens: z.number().int().min(1).max(32000).default(4096),`,
    `    Forward them to chat({ ctx, baseUrl, apiKey, model, temperature, maxTokens, ... }).`,
    `    Mark api_key with fieldMeta { secret: true } so the Studio masks it.`,
    "  - Call `defineNode({ type, typeVersion, title, description,",
    "    config, ports, validateInput: false, run })`.",
    "    - `type` MUST equal `nodeSpec.nodeType` exactly.",
    "    - `typeVersion` MUST equal `nodeSpec.typeVersion`.",
    "    - `ports` includes ONLY the data/error ports from `inputPorts`",
    "      and `outputPorts`. Do NOT include `in` / `out` / `error`;",
    "      defineNode adds those automatically.",
    "      Preserve `multiple: true` on any declared port that has it.",
    "  - Implement `run({ input, config, ctx })`:",
    "      - Cast `input` once: `const raw = input as Record<string, unknown>;`",
    "      - Read each declared input port from `raw`.",
    "      - Root nodes may have no declared input ports. In that case read the original caller payload from `raw.__runInput__`, falling back to `raw.input` or `raw.in`.",
    "      - Downstream nodes may receive a control-only fallback. If a declared input is empty, consider `raw.input` / `raw.in` as the upstream primary data value.",
    "      - Preserve cumulative context: when a `context` input/output port exists, merge prior context into the output instead of replacing it wholesale.",
    "      - If `raw.context` is an array, merge the entries in order before applying this node's own result.",
    "      - Apply the strategy:",
    `         - "llm_prompt": import { chat } or { chatJson } from "./_llm.js".`,
    "             Render `nodeSpec.implementation.promptTemplate` by",
    `             substituting "\${input.X}" with String(raw.X).`,
    `             If responseFormat is "json", parse the assistant text`,
    "             and validate with a small zod schema.",
    `         - "transform": pure-TS implementation of`,
    "             nodeSpec.implementation.transformLogic.",
    `         - "external_call": use global fetch (no extra deps) or call`,
    "             the named tool. If the tool requires credentials,",
    "             read them via `ctx.secrets.get(...)`.",
    "      - Return `{ kind: 'success', outputs: { out: null, ...portsByName } }`",
    "        OR on failure `{ kind: 'error', error: { code, message, kind, category } }`.",
    "  - Catch unknown errors and surface them as a structured error result.",
    "  - Use `ctx.log.info(...)` for milestones, `ctx.log.warn(...)` for soft issues.",
    "  - Keep the file under 250 lines. No tests. No `console.log`.",
    "  - The exported binding name must be the camelCased nodeType + 'Node',",
    "    e.g. nodeType `parse_user_input` -> `export const parseUserInputNode = defineNode({...})`.",
    "",
    "EXAMPLE (LLM-prompt strategy):",
    "```ts",
    `import { defineNode } from "@ai-native-flow/node-sdk";`,
    `import { z } from "zod";`,
    `import { chat } from "./_llm.js";`,
    "",
    `const config = z.object({`,
    `  base_url: z.string().min(1).default("$var:LLM_BASE_URL"),`,
    `  api_key: z.string().min(1).default("$var:LLM_API_KEY"),`,
    `  model: z.string().min(1).default("$var:LLM_DEFAULT_MODEL"),`,
    `  temperature: z.number().min(0).max(2).default(0),`,
    `  max_tokens: z.number().int().min(1).max(32000).default(4096),`,
    `}).passthrough();`,
    "",
    `export const summarizeTextNode = defineNode({`,
    `  type: "summarize_text",`,
    `  typeVersion: "1.0.0",`,
    `  title: "摘要文本",`,
    `  description: "Summarise the user-supplied text via the configured LLM.",`,
    `  config,`,
    `  fieldMeta: {`,
    `    base_url: { label: "URL", order: 1 },`,
    `    api_key:  { label: "APIKEY", secret: true, order: 2 },`,
    `    model:    { label: "Model", order: 3 },`,
    `    temperature: { label: "Temperature", order: 4 },`,
    `    max_tokens: { label: "Max Tokens", order: 5 },`,
    `  },`,
    `  ports: [`,
    `    { id: "user_text", direction: "input", kind: "data", label: "User text" },`,
    `    { id: "summary", direction: "output", kind: "data", label: "Summary", schema: { type: "string" } },`,
    `  ],`,
    `  validateInput: false,`,
    `  async run({ input, config, ctx }) {`,
    `    const raw = input as Record<string, unknown>;`,
    `    const text = String(raw.user_text ?? "");`,
    `    if (!text) {`,
    `      return { kind: "error", error: { code: "node.summarize_text.empty_input", message: "user_text is empty", kind: "validation", category: "user_input" } };`,
    `    }`,
    `    try {`,
    `      const result = await chat({`,
    `        system: "You are a concise analyst.",`,
    `        user: \`Summarize the following:\\n\\n\${text}\`,`,
    `        baseUrl: config.base_url || undefined,`,
    `        apiKey:  config.api_key  || undefined,`,
    `        model:   config.model    || undefined,`,
    `        temperature: config.temperature,`,
    `        maxTokens: config.max_tokens,`,
    `        signal: ctx.signal,`,
    `        ctx,`,
    `      });`,
    `      return { kind: "success", outputs: { out: null, summary: result.text } };`,
    `    } catch (cause) {`,
    `      return { kind: "error", error: { code: "node.summarize_text.llm_failed", message: (cause as Error).message, kind: "external", category: "external" } };`,
    `    }`,
    `  },`,
    `});`,
    "```",
    "",
    "Output JSON only.",
  ].join("\n");
}

function validateSynthesizerSpecs(specs: readonly NodeSpec[]): string | null {
  const builtinTypes = new Set(getBuiltinNodeDefinitions().map((def) => def.type));
  const seen = new Set<string>();
  for (const spec of specs) {
    if (builtinTypes.has(spec.nodeType)) {
      return `generated nodeType "${spec.nodeType}"@${spec.typeVersion} conflicts with a runtime built-in node; use a skill-scoped custom nodeType instead`;
    }
    if (seen.has(spec.nodeType)) {
      return `duplicate generated nodeType "${spec.nodeType}"`;
    }
    seen.add(spec.nodeType);
  }
  return null;
}

function buildUserPrompt(
  skill: SkillDefinition,
  plan: ExecutionPlan,
  spec: NodeSpec,
  step: ExecutionPlan["steps"][number] | undefined,
): string {
  const cfg = spec.configFields
    .map(
      (f) =>
        `  - ${f.name} (${f.type}, ${f.required ? "required" : "optional"})${
          f.default !== undefined
            ? ` default=${JSON.stringify(f.default)}`
            : ""
        }: ${f.description}`,
    )
    .join("\n");
  const inPorts = spec.inputPorts
    .map((p) => `  - ${p.id} (${p.dataType}${p.multiple ? ", multiple" : ""}) - ${p.label}`)
    .join("\n");
  const outPorts = spec.outputPorts
    .map(
      (p) =>
        `  - ${p.id} (${p.dataType}, ${p.kind}${p.multiple ? ", multiple" : ""}) - ${p.label}`,
    )
    .join("\n");

  return [
    `# SKILL CONTEXT`,
    `name: ${skill.name}`,
    `description: ${skill.description || "(empty)"}`,
    `planSummary: ${plan.summary}`,
    "",
    `# REQUIREMENTS`,
    formatRequirements(plan),
    "",
    `# PLAN STEP`,
    step
      ? [
          `id: ${step.id}`,
          `kind: ${step.kind}`,
          `dependencies: ${step.dependencies.join(", ") || "(none - root step)"}`,
          `intent: ${step.intent}`,
        ].join("\n")
      : `id: ${spec.stepId}`,
    "",
    `# NODE SPEC`,
    `nodeType: ${spec.nodeType}`,
    `typeVersion: ${spec.typeVersion}`,
    `title: ${spec.title}`,
    `description: ${spec.description}`,
    "",
    `## Config fields`,
    cfg || "  (none)",
    "",
    `## Input ports (excluding control)`,
    inPorts || "  (none)",
    "",
    `## Output ports (excluding control & error)`,
    outPorts || "  (none)",
    "",
    `## Implementation`,
    `strategy: ${spec.implementation.strategy}`,
    spec.implementation.strategy === "llm_prompt"
      ? `responseFormat: ${spec.implementation.responseFormat ?? "text"}\npromptTemplate:\n${spec.implementation.promptTemplate ?? ""}`
      : spec.implementation.strategy === "transform"
        ? `transformLogic:\n${spec.implementation.transformLogic ?? ""}`
        : `tool: ${spec.implementation.tool ?? ""}\ncallDescription: ${spec.implementation.callDescription ?? ""}`,
    "",
    `## Pseudocode`,
    spec.pseudocode,
    "",
    `## Runtime input and context contract`,
    step?.dependencies.length === 0
      ? "This is a root node. It has no data input edge from start. Read the caller payload from raw.__runInput__, with raw.input/raw.in as fallbacks."
      : "This is a downstream node. Read declared data ports first. If no declared data value is present, raw.input/raw.in may contain the primary upstream output supplied through a control-only fallback.",
    "When a `context` port exists, treat it as the cumulative state object. Merge this step's result into it instead of discarding prior context. If the context input is an array, merge the array entries first.",
    "",
    "Produce the JSON { filePath, source } now.",
  ].join("\n");
}

function formatRequirements(plan: ExecutionPlan): string {
  const req = plan.requirements;
  if (!req) return "(none supplied)";
  return [
    `Goals: ${req.goals.length ? req.goals.join("; ") : "(none)"}`,
    `Input contract: ${
      req.inputContract.length
        ? req.inputContract
            .map((item) => `${item.name} (${item.dataType}) — ${item.description}`)
            .join("; ")
        : "(none)"
    }`,
    `Output contract: ${
      req.outputContract.length
        ? req.outputContract
            .map((item) => `${item.name} (${item.dataType}) — ${item.description}`)
            .join("; ")
        : "(none)"
    }`,
    `Acceptance criteria: ${
      req.acceptanceCriteria.length ? req.acceptanceCriteria.join("; ") : "(none)"
    }`,
    `Constraints: ${req.constraints.length ? req.constraints.join("; ") : "(none)"}`,
    `Context handoff: ${req.contextHandoff || "(none)"}`,
  ].join("\n");
}

/* -------------------------------------------------------------------------- */
/* deterministic flow assembly                                                */
/* -------------------------------------------------------------------------- */

interface AssemblyResult {
  json: string;
  graph: unknown;
}

type BuiltNodeHandle = ReturnType<FlowBuilder["node"]>;

function assembleFlowGraph(
  skill: SkillDefinition,
  plan: ExecutionPlan,
  specs: readonly NodeSpec[],
  flowVersion: string,
): AssemblyResult {
  const flowId = sanitizeFlowId(skill.name);
  const specByStep = new Map<string, NodeSpec>();
  for (const s of specs) specByStep.set(s.stepId, s);

  // Build a registry containing every synthesised type so the
  // flow-builder accepts our edges.
  const registry = createDefaultRegistry();
  const builtinTypes = new Set<string>();
  for (const def of getBuiltinNodeDefinitions()) {
    builtinTypes.add(def.type);
    if (!registry.has(def.type, def.typeVersion)) registry.register(def);
  }
  for (const spec of specs) {
    if (builtinTypes.has(spec.nodeType)) {
      throw new Error(
        `generated nodeType "${spec.nodeType}"@${spec.typeVersion} conflicts with a runtime built-in node; use a skill-scoped custom nodeType instead`,
      );
    }
    const def: NodeTypeDefinition = {
      type: spec.nodeType,
      typeVersion: spec.typeVersion,
      title: spec.title,
      defaultPorts: [
        { id: "in", direction: "input", kind: "control", label: "In" },
        { id: "out", direction: "output", kind: "control", label: "Out" },
        ...spec.inputPorts.map((p) => ({
          id: p.id,
          direction: "input" as const,
          kind: p.kind,
          label: p.label || p.id,
          ...(p.multiple !== undefined ? { multiple: p.multiple } : {}),
        })),
        ...spec.outputPorts.map((p) => ({
          id: p.id,
          direction: "output" as const,
          kind: p.kind,
          label: p.label || p.id,
          ...(p.multiple !== undefined ? { multiple: p.multiple } : {}),
        })),
        { id: "error", direction: "output", kind: "error", label: "Error" },
      ],
      runtime: "builtin",
    };
    registry.register(def);
  }

  const flow = defineFlow({
    id: flowId,
    version: flowVersion,
    label: `${skill.name} 自动生成 Flow`,
    description: plan.summary,
    inputSchema: { type: "object" },
    registry,
  });

  // Lay nodes out in topo bands (best-effort, only for visual sanity).
  const bands = computeTopoBands(plan);
  const handles = new Map<string, ReturnType<typeof flow.node>>();

  // Pseudo-nodes.
  const start = flow.node("start", {
    id: "node_start",
    label: "Start",
    position: { x: -200, y: 0 },
  });
  const end = flow.node("end", {
    id: "node_end",
    label: "End",
    position: { x: (bands.length + 1) * 320 + 100, y: 0 },
  });

  // Custom nodes.
  for (let bandIdx = 0; bandIdx < bands.length; bandIdx += 1) {
    const band = bands[bandIdx]!;
    band.forEach((stepId, rowIdx) => {
      const spec = specByStep.get(stepId);
      const step = plan.steps.find((s) => s.id === stepId);
      if (!spec || !step) return;
      const handle = flow.node(spec.nodeType, {
        id: stepId,
        label: step.label,
        position: {
          x: 100 + bandIdx * 320,
          y: -((band.length - 1) * 90) + rowIdx * 180,
        },
        config: defaultConfigFor(spec),
      });
      handles.set(stepId, handle);
    });
  }

  // Wiring.
  const hasOutgoing = new Set<string>();
  const filledInputsByStep = new Map<string, Set<string>>();
  for (const step of plan.steps) {
    const handle = handles.get(step.id);
    if (!handle) continue;

    if (step.dependencies.length === 0) {
      // Root steps get a control edge from start.
      flow.connect(start.out("out"), handle.in("in"));
    } else {
      // Wire matching data ports from each upstream dep.
      for (const dep of step.dependencies) {
        const depHandle = handles.get(dep);
        const depSpec = specByStep.get(dep);
        if (!depHandle || !depSpec) continue;
        hasOutgoing.add(dep);

        const connected = connectDataWithContextFallback({
          flow,
          depHandle,
          depSpec,
          targetHandle: handle,
          targetSpec: specByStep.get(step.id)!,
          filledInputs:
            filledInputsByStep.get(step.id) ??
            filledInputsByStep.set(step.id, new Set()).get(step.id)!,
        });

        // If no data port pair was found, fall back to a control edge so
        // the downstream node still triggers. The runtime then exposes the
        // upstream primary data output as raw.input/raw.in.
        if (connected === 0) {
          flow.connect(depHandle.out("out"), handle.in("in"));
        }
      }
    }
  }

  // Leaves -> end (control only).
  for (const step of plan.steps) {
    if (hasOutgoing.has(step.id)) continue;
    const handle = handles.get(step.id);
    if (!handle) continue;
    flow.connect(handle.out("out"), end.in("in"));
  }

  const json = flow.dump();
  return { json, graph: JSON.parse(json) };
}

function connectDataWithContextFallback(args: {
  flow: FlowBuilder;
  depHandle: BuiltNodeHandle;
  depSpec: NodeSpec;
  targetHandle: BuiltNodeHandle;
  targetSpec: NodeSpec;
  filledInputs: Set<string>;
}): number {
  const dataOutputs = args.depSpec.outputPorts.filter((p) => p.kind === "data");
  const dataInputs = args.targetSpec.inputPorts.filter((p) => p.kind === "data");
  let connected = 0;

  // First pass: exact port-id matches keep the LLM-designed data contract.
  for (const out of dataOutputs) {
    const input = dataInputs.find(
      (p) =>
        p.id === out.id && (p.multiple || !args.filledInputs.has(p.id)),
    );
    if (!input) continue;
    args.flow.connect(args.depHandle.out(out.id), args.targetHandle.in(input.id));
    if (!input.multiple) args.filledInputs.add(input.id);
    connected += 1;
  }

  if (connected > 0) return connected;

  // Second pass: semantic fallback. If the planner/designer chose different
  // names for adjacent ports, still pass the upstream primary data object into
  // the first unfilled downstream input instead of dropping context.
  const source =
    dataOutputs.find((p) => p.id === "context") ??
    dataOutputs.find((p) => p.kind === "data");
  const target =
    dataInputs.find(
      (p) =>
        p.id === "context" && (p.multiple || !args.filledInputs.has(p.id)),
    ) ??
    dataInputs.find((p) => !args.filledInputs.has(p.id));

  if (!source || !target) return 0;

  args.flow.connect(args.depHandle.out(source.id), args.targetHandle.in(target.id));
  if (!target.multiple) args.filledInputs.add(target.id);
  return 1;
}

function computeTopoBands(plan: ExecutionPlan): string[][] {
  const depth = new Map<string, number>();
  const stepById = new Map<string, (typeof plan.steps)[number]>();
  for (const s of plan.steps) stepById.set(s.id, s);

  const visit = (id: string, stack: Set<string>): number => {
    if (depth.has(id)) return depth.get(id)!;
    if (stack.has(id)) return 0; // defensive - already validated upstream
    stack.add(id);
    const step = stepById.get(id);
    if (!step) return 0;
    let d = 0;
    for (const dep of step.dependencies) d = Math.max(d, visit(dep, stack) + 1);
    stack.delete(id);
    depth.set(id, d);
    return d;
  };
  for (const s of plan.steps) visit(s.id, new Set());

  const bands: string[][] = [];
  for (const [id, d] of depth.entries()) {
    if (!bands[d]) bands[d] = [];
    bands[d]!.push(id);
  }
  return bands.filter(Boolean);
}

function defaultConfigFor(spec: NodeSpec): Record<string, unknown> {
  const out: Record<string, unknown> = {};
  for (const f of spec.configFields) {
    if (f.default !== undefined) out[f.name] = f.default;
  }
  return out;
}

/* -------------------------------------------------------------------------- */
/* boilerplate renderers                                                      */
/* -------------------------------------------------------------------------- */

function renderNodesIndex(skillName: string, specs: readonly NodeSpec[]): string {
  const imports = specs
    .map(
      (s) =>
        `import { ${nodeBindingName(s)} } from "./${toCamelCase(s.nodeType)}.js";`,
    )
    .join("\n");
  const list = specs.map((s) => `    ${nodeBindingName(s)},`).join("\n");
  return [
    `/**`,
    ` * Node-pack entry for the ${skillName} flow (auto-generated).`,
    ` */`,
    `import type { DefinedNode } from "@ai-native-flow/node-sdk";`,
    "",
    imports,
    "",
    `export default function createNodes(`,
    `  _deps: Record<string, unknown> = {},`,
    `): DefinedNode[] {`,
    `  return [`,
    list,
    `  ];`,
    `}`,
    "",
  ].join("\n");
}

function renderBuildTs(
  skill: SkillDefinition,
  flowId: string,
  flowVersion: string,
  specs: readonly NodeSpec[],
): string {
  const imports = specs
    .map(
      (s) =>
        `import { ${nodeBindingName(s)} } from "./nodes/${toCamelCase(s.nodeType)}.js";`,
    )
    .join("\n");
  const installs = specs
    .map((s) => `  installNode(adapter, ${nodeBindingName(s)});`)
    .join("\n");
  return [
    `/**`,
    ` * Build script for the ${skill.name} flow (auto-generated).`,
    ` *`,
    ` * Run with: tsx build.ts`,
    ` */`,
    `import { readFileSync } from "node:fs";`,
    `import path from "node:path";`,
    `import { fileURLToPath } from "node:url";`,
    "",
    `import { createDefaultRegistry, type FlowGraph } from "@ai-native-flow/flow-ir";`,
    `import { validateGraph } from "@ai-native-flow/flow-validator";`,
    `import { installNode } from "@ai-native-flow/node-sdk";`,
    `import { getBuiltinNodeDefinitions } from "@ai-native-flow/runtime";`,
    "",
    imports,
    "",
    `const __dirname = path.dirname(fileURLToPath(import.meta.url));`,
    `const FLOW_JSON_PATH = path.join(__dirname, "flows", "${flowId}.json");`,
    "",
    `export function buildRegistry() {`,
    `  const registry = createDefaultRegistry();`,
    `  const builtinTypes = new Set<string>();`,
    `  for (const def of getBuiltinNodeDefinitions()) {`,
    `    builtinTypes.add(def.type);`,
    `    if (!registry.has(def.type, def.typeVersion)) registry.register(def);`,
    `  }`,
    `  const adapter = {`,
    `    registerType: (def: any) => {`,
    `      if (builtinTypes.has(def.type)) {`,
    `        throw new Error(\`generated nodeType "\${def.type}"@\${def.typeVersion ?? "1.0.0"} conflicts with a runtime built-in node; use a skill-scoped custom nodeType instead\`);`,
    `      }`,
    `      registry.register(def);`,
    `    },`,
    `    registerRunner: () => undefined,`,
    `  };`,
    installs,
    `  return registry;`,
    `}`,
    "",
    `if (process.argv[1]?.endsWith("build.ts")) {`,
    `  // The Flow JSON is regenerated by re-running skill-to-flow; this`,
    `  // script validates the bundled artefact against the generated node`,
    `  // registry so materialization failures surface before runtime.`,
    `  const json = readFileSync(FLOW_JSON_PATH, "utf8");`,
    `  const graph = JSON.parse(json) as FlowGraph;`,
    `  const result = validateGraph(graph, { registry: buildRegistry() });`,
    `  if (result.errors.length > 0) {`,
    `    for (const error of result.errors) {`,
    `      console.error(\`\${error.code}: \${error.message}\`);`,
    `    }`,
    `    process.exitCode = 1;`,
    `  } else {`,
    `    for (const warning of result.warnings) {`,
    `      console.warn(\`\${warning.code}: \${warning.message}\`);`,
    `    }`,
    `    console.log(\`OK: \${FLOW_JSON_PATH} (\${json.length} bytes, warnings=\${result.warnings.length})\`);`,
    `  }`,
    `}`,
    "",
  ].join("\n");
}

function renderRuntimeTs(
  skill: SkillDefinition,
  flowId: string,
  flowVersion: string,
  specs: readonly NodeSpec[],
): string {
  const imports = specs
    .map(
      (s) =>
        `import { ${nodeBindingName(s)} } from "./nodes/${toCamelCase(s.nodeType)}.js";`,
    )
    .join("\n");
  const list = specs.map((s) => `    ${nodeBindingName(s)},`).join("\n");
  return [
    `/**`,
    ` * Shared runtime factory for the ${skill.name} flow (auto-generated).`,
    ` *`,
    ` * Reads the bundled \`flows/${flowId}.json\`, registers all custom`,
    ` * nodes and promotes the flow to active.`,
    ` */`,
    `import { readFileSync } from "node:fs";`,
    `import path from "node:path";`,
    `import { fileURLToPath } from "node:url";`,
    "",
    `import { createRuntime, type Runtime } from "@ai-native-flow/runtime";`,
    `import type { SecretStore, VariableStore } from "@ai-native-flow/variable-store";`,
    `import type { FlowGraph } from "@ai-native-flow/flow-ir";`,
    "",
    imports,
    "",
    `const __dirname = path.dirname(fileURLToPath(import.meta.url));`,
    `export const FLOW_ID = "${flowId}";`,
    `export const FLOW_VERSION = "${flowVersion}";`,
    `export const FLOW_JSON_PATH = path.join(__dirname, "flows", "${flowId}.json");`,
    "",
    `export interface CreateRuntimeOptions {`,
    `  skipFlowRegistration?: boolean;`,
    `  variables?: VariableStore;`,
    `  /** @deprecated Use variables; treated as the same store. */`,
    `  secrets?: SecretStore;`,
    `}`,
    "",
    `export async function create${pascalCase(flowId)}Runtime(`,
    `  options: CreateRuntimeOptions = {},`,
    `): Promise<Runtime> {`,
    `  // LLM endpoint is read from the stores supplied by the caller.`,
    `  // Missing LLM config is not synthesized here; the runtime provider`,
    `  // reports the exact missing variable when an LLM node runs.`,
    "",
    `  const runtime = createRuntime({`,
    `    variables: options.variables,`,
    `    secrets: options.secrets,`,
    `    nodes: [`,
    list,
    `    ],`,
    `  });`,
    "",
    `  if (!options.skipFlowRegistration) {`,
    `    const json = readFileSync(FLOW_JSON_PATH, "utf8");`,
    `    const graph: FlowGraph = JSON.parse(json);`,
    `    await runtime.registry.register({ graph, json });`,
    `    await runtime.registry.promote(graph.id, graph.version);`,
    `  }`,
    "",
    `  return runtime;`,
    `}`,
    "",
    `export { create${pascalCase(flowId)}Runtime as createRuntime };`,
    "",
  ].join("\n");
}

function renderCliTs(flowId: string): string {
  return [
    `/**`,
    ` * CLI entrypoint for the ${flowId} generated flow.`,
    ` *`,
    ` * Usage:`,
    ` *   tsx cli.ts run ${flowId} --input '{}'`,
    ` *   tsx cli.ts inspect <runId>`,
    ` *   tsx cli.ts replay <runId>`,
    ` */`,
    "",
    `import { runFlowCli } from "@ai-native-flow/transport-cli/bootstrap";`,
    "",
    `import { createRuntime } from "./runtime.js";`,
    "",
    `const runtime = await createRuntime();`,
    `const result = await runFlowCli({ runtime });`,
    `process.exit(result.exitCode);`,
    "",
  ].join("\n");
}

function renderPackageJson(skill: SkillDefinition, flowId: string): string {
  return `${JSON.stringify(
    {
      name: `generated-${flowId.replace(/_/g, "-")}`,
      version: "0.0.0",
      private: true,
      type: "module",
      description: skill.description || `Generated Flow package for ${skill.name}`,
      scripts: {
        build: "tsx build.ts",
        run: `tsx cli.ts run ${flowId} --input '{}'`,
        typecheck: "tsc --noEmit -p tsconfig.json",
      },
      dependencies: {
        "@ai-native-flow/flow-ir": "0.0.1",
        "@ai-native-flow/flow-validator": "0.0.1",
        "@ai-native-flow/node-sdk": "0.0.1",
        "@ai-native-flow/runtime": "0.0.1",
        "@ai-native-flow/transport-cli": "0.0.1",
        "@ai-native-flow/variable-store": "0.0.1",
        zod: "^3.23.8",
      },
      devDependencies: {
        "@types/node": "^20.12.7",
        tsx: "^4.20.4",
        typescript: "^5.5.4",
      },
      engines: {
        node: ">=20.11.0",
      },
    },
    null,
    2,
  )}\n`;
}

function renderTsconfigJson(): string {
  return `${JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "NodeNext",
        moduleResolution: "NodeNext",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        noEmit: true,
        types: ["node"],
      },
      include: ["*.ts", "nodes/**/*.ts"],
    },
    null,
    2,
  )}\n`;
}

function renderReadme(
  skill: SkillDefinition,
  plan: ExecutionPlan,
  specs: readonly NodeSpec[],
  flowId: string,
): string {
  const stepsTable = plan.steps
    .map((s) => {
      const sp = specs.find((sp) => sp.stepId === s.id);
      return `| ${s.id} | ${s.kind} | ${sp?.nodeType ?? "?"} | ${s.description} |`;
    })
    .join("\n");
  return [
    `# ${skill.name}`,
    "",
    `> ${skill.description || "(no description)"}`,
    "",
    `This package was generated by \`@ai-native-flow/skill-to-flow\`.`,
    `It converts SKILL.md into a runnable Flow package.`,
    "",
    `## Requirements`,
    "",
    renderRequirementsMarkdown(plan),
    "",
    `## Structure`,
    "",
    `- \`build.ts\` validates the bundled Flow JSON against the generated node registry`,
    `- \`runtime.ts\` exposes a factory for CLI / HTTP / tests`,
    `- \`cli.ts\` runs the generated flow through @ai-native-flow/transport-cli`,
    `- \`package.json\` declares the minimal runnable app package`,
    `- \`tsconfig.json\` enables static TypeScript validation`,
    `- \`flows/${flowId}.json\` contains the generated FlowGraph`,
    `- \`nodes/\` contains ${specs.length} custom nodes`,
    "",
    `## Plan`,
    "",
    plan.summary,
    "",
    `| Step ID | Kind | Node Type | Description |`,
    `|---|---|---|---|`,
    stepsTable,
    "",
    `## 运行`,
    "",
    `\`\`\`bash`,
    `npm install`,
    `tsx build.ts`,
    `npm run typecheck`,
    `tsx cli.ts run ${flowId} --input '{}'`,
    `\`\`\``,
    "",
  ].join("\n");
}

function normalizePackageRequirements(plan: ExecutionPlan): SkillRequirements {
  return skillRequirementsSchema.parse(plan.requirements ?? {});
}

function renderRequirementsMarkdown(plan: ExecutionPlan): string {
  const req = normalizePackageRequirements(plan);
  return [
    `### Goals`,
    renderBulletList(req.goals),
    "",
    `### Input Contract`,
    renderIoList(req.inputContract),
    "",
    `### Output Contract`,
    renderIoList(req.outputContract),
    "",
    `### Acceptance Criteria`,
    renderBulletList(req.acceptanceCriteria),
    "",
    `### Constraints`,
    renderBulletList(req.constraints),
    "",
    `### Context Handoff`,
    "",
    req.contextHandoff || "(none)",
  ].join("\n");
}

function renderBulletList(items: readonly string[]): string {
  if (!items.length) return "- (none)";
  return items.map((item) => `- ${item}`).join("\n");
}

function renderIoList(
  items: ReadonlyArray<{ name: string; dataType: string; description: string }>,
): string {
  if (!items.length) return "- (none)";
  return items
    .map((item) => `- \`${item.name}\` (${item.dataType}): ${item.description}`)
    .join("\n");
}

/* -------------------------------------------------------------------------- */
/* helpers                                                                     */
/* -------------------------------------------------------------------------- */

function nodeBindingName(spec: NodeSpec): string {
  return `${toCamelCase(spec.nodeType)}Node`;
}

function toCamelCase(snake: string): string {
  return snake.replace(/_([a-z0-9])/g, (_, ch: string) => ch.toUpperCase());
}

function pascalCase(snake: string): string {
  const camel = toCamelCase(snake);
  return camel.charAt(0).toUpperCase() + camel.slice(1);
}

function sanitizeFlowId(skillName: string): string {
  return (
    skillName
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "") || "generated_flow"
  );
}

/**
 * Light safety net: if the LLM omitted the type literal we paste it
 * back in as a comment so the linter in `flow_validator` reports a
 * clear hint instead of a generic "type not found" warning.
 */
function ensureSourceMentionsType(source: string, nodeType: string): string {
  if (source.includes(`type: "${nodeType}"`)) return source;
  return `${source}\n\n// skill-to-flow: expected nodeType "${nodeType}" - verify the defineNode call above\n`;
}

export const __testing = {
  assembleFlowGraph,
  buildUserPrompt,
  renderBuildTs,
  renderCliTs,
  renderPackageJson,
  renderReadme,
  renderTsconfigJson,
  renderRuntimeTs,
  validateSynthesizerSpecs,
  get bundledLlmSource() {
    return BUNDLED_LLM_TS;
  },
};

/* -------------------------------------------------------------------------- */
/* bundled _llm.ts (kept in sync with apps/skill-to-flow/nodes/_llm.ts)       */
/* -------------------------------------------------------------------------- */

const BUNDLED_LLM_TS = `/**
 * _llm.ts - chat helper bundled with the generated package.
 *
 * This helper does not hand-roll vendor communication. It delegates to
 * the runtime LlmProvider boundary, whose production implementation uses
 * Vercel AI SDK's OpenAI-compatible provider.
 */
import {
  AiSdkOpenAICompatibleLlmProvider,
  type LlmCompletionRequest,
  type NodeContext,
} from "@ai-native-flow/runtime";

export interface ChatOptions {
  system?: string;
  user: string;
  model?: string;
  temperature?: number;
  baseUrl?: string;
  apiKey?: string;
  maxTokens?: number;
  signal?: AbortSignal;
  ctx: unknown;
  jsonMode?: boolean;
}

export interface ChatResult {
  text: string;
  raw?: unknown;
}

const provider = new AiSdkOpenAICompatibleLlmProvider({
  providerName: "skill-to-flow-generated",
});

function buildPrompt(o: ChatOptions): string {
  const parts: string[] = [];
  if (o.system && o.system.trim()) parts.push(\`System:\\n\${o.system}\`);
  const user = o.jsonMode
    ? \`\${o.user}\\n\\nReturn ONLY one valid JSON object. No prose, no markdown fences.\`
    : o.user;
  parts.push(\`User:\\n\${user}\`);
  return parts.join("\\n\\n");
}

export async function chat(o: ChatOptions): Promise<ChatResult> {
  const request: LlmCompletionRequest = {
    prompt: buildPrompt(o),
    ...(o.model !== undefined ? { model: o.model } : {}),
    temperature: o.temperature ?? 0,
    ...(o.maxTokens !== undefined ? { maxTokens: o.maxTokens } : {}),
    ...(o.baseUrl !== undefined ? { baseUrl: o.baseUrl } : {}),
    ...(o.apiKey !== undefined ? { apiKey: o.apiKey } : {}),
  };
  const result = await provider.complete(request, o.ctx as NodeContext);
  return { text: result.text, raw: result.raw };
}

export async function chatJson<T>(
  o: ChatOptions & { schema: { safeParse: (v: unknown) => { success: boolean; data?: T; error?: { issues: any[] } } }; maxRetries?: number },
): Promise<T> {
  const max = o.maxRetries ?? 2;
  let lastErr = "";
  for (let i = 0; i <= max; i += 1) {
    const userPrompt =
      i === 0
        ? o.user
        : \`\${o.user}\\n\\n---\\nPrevious response failed: \${lastErr}\\nReturn ONLY valid JSON.\`;
    const r = await chat({ ...o, user: userPrompt, jsonMode: true });
    let s = r.text.trim();
    if (s.charCodeAt(0) === 0xfeff) s = s.slice(1);
    const fence = /^\\\`\\\`\\\`(?:json)?\\s*([\\s\\S]*?)\\s*\\\`\\\`\\\`$/i.exec(s);
    if (fence && fence[1]) s = fence[1].trim();
    let parsed: unknown;
    try {
      parsed = JSON.parse(s);
    } catch (e) {
      lastErr = \`parse: \${(e as Error).message}\`;
      continue;
    }
    const c = o.schema.safeParse(parsed);
    if (c.success && c.data !== undefined) return c.data;
    lastErr = c.error
      ? c.error.issues
          .map((iss) => \`\${(iss.path ?? []).join(".")}: \${iss.message}\`)
          .join("; ")
      : "schema mismatch";
  }
  throw new Error(\`chatJson exhausted retries: \${lastErr}\`);
}
`;

